import {createRequire} from'node:module';import {mkdir} from'node:fs/promises';import path from'node:path';import{fileURLToPath,pathToFileURL}from'node:url';
const here=path.dirname(fileURLToPath(import.meta.url)),req=createRequire(import.meta.url);let pw;for(const c of[process.env.PLAYWRIGHT_MODULE_PATH,'playwright'].filter(Boolean))try{pw=req(c);break}catch{}if(!pw)throw Error('Set PLAYWRIGHT_MODULE_PATH');
const browser=await pw.chromium.launch(process.env.PLAYWRIGHT_EXECUTABLE_PATH?{executablePath:process.env.PLAYWRIGHT_EXECUTABLE_PATH}:{}),page=await browser.newPage({viewport:{width:390,height:844}}),fail=[],errors=[];
page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});page.on('requestfailed',r=>errors.push(r.url()));page.on('dialog',d=>d.accept());
const check=(n,v,d='')=>{console.log(`${v?'PASS':'FAIL'} ${n} ${d}`);if(!v)fail.push(n)},url=pathToFileURL(path.join(here,'index.html')).href+'?seed=777&fresh=v07',state=()=>page.evaluate(()=>debugState());
const artifactDirectory=path.resolve(process.env.VOXEL_ARTIFACT_DIR||path.join(here,'../../artifacts/voxel-mine'));await mkdir(artifactDirectory,{recursive:true});
async function fresh(){await page.goto(url);await page.waitForFunction(()=>typeof debugState==='function');await page.evaluate(()=>resetGame())}
try{
await fresh();let s=await state();check('Initial gear capacity 6, empty loadout, workshop locked',s.player.gearCapacity===6&&!s.player.gears.length&&!s.player.equippedGearIds.length&&!s.player.workshopUnlocked);
await page.evaluate(()=>{player.gears.push({id:'x',name:'x',trait:'fuel',weight:2});player.workshopUnlocked=true;debugSave();resetGame()});s=await state();check('Debug reset clears v0.7 progression',!s.player.gears.length&&!s.player.workshopUnlocked&&s.player.gearCapacity===6);
await page.evaluate(()=>localStorage.setItem(saveKey(),JSON.stringify({version:7,worldSeed,player:{coins:999},island:{}})));await page.reload();await page.waitForFunction(()=>typeof debugState==='function');s=await state();check('Old save schema initializes fresh schema 8',s.player.coins===0&&JSON.parse(await page.evaluate(()=>localStorage.getItem(saveKey()))).version===8);

const loot=await page.evaluate(()=>{debugDepart(1);const a=createTreasure('same'),b=createTreasure('same'),many=Array.from({length:12},(_,i)=>createTreasure('v'+i)),kept=gainTreasure('kept');debugSave();return{a,b,many,kept}});
check('Treasure individual is deterministic with name/value/flavor',JSON.stringify(loot.a)===JSON.stringify(loot.b)&&loot.a.name&&loot.a.value>0&&loot.a.flavor);check('Treasure sources produce varied individuals',new Set(loot.many.map(x=>x.name+'|'+x.value+'|'+x.flavor)).size>=4);await page.reload();check('Treasure individual persists on reload',await page.evaluate(x=>JSON.stringify(player.treasures.find(y=>y.id===x.id))===JSON.stringify(x),loot.kept));

await page.evaluate(()=>{expedition.returnRequested=true;expedition.returnReason='manual';finishReturn();acknowledgeResult()});const gear=await page.evaluate(()=>{player.gears=[{id:'p',name:'P',trait:'power',weight:2},{id:'f',name:'F',trait:'fuel',weight:2},{id:'c',name:'C',trait:'chain',weight:2},{id:'e',name:'E',trait:'appraisal',weight:1}];player.equippedGearIds=[];const base=[hitPower(),fuelCapacity(),chainCount()],toggles=['p','f','c','e'].map(debugToggleGear),equipped={ids:[...player.equippedGearIds],weight:equippedWeight(),stats:[hitPower(),fuelCapacity(),chainCount()]};debugDepart(1);const before=JSON.stringify(player.equippedGearIds),outside=debugToggleGear('p');return{base,toggles,equipped,outside,unchanged:before===JSON.stringify(player.equippedGearIds)}});
check('Gear enforces weight 6 and maximum 3',gear.toggles.slice(0,3).every(Boolean)&&!gear.toggles[3]&&gear.equipped.weight===6&&gear.equipped.ids.length===3);check('Equipped gear effects apply',gear.equipped.stats[0]===gear.base[0]+1&&gear.equipped.stats[1]===gear.base[1]+6&&gear.equipped.stats[2]===gear.base[2]+2);check('Gear changes are port-only',!gear.outside&&gear.unchanged);

await fresh();const drillCopy=await page.evaluate(()=>{const text=document.body.innerText;return{old:(text.match(/つるはし/g)||[]).length,drill:text.includes('船外削岩機'),power:text.includes('削岩出力'),blocked:!debugCraft('pickaxe')}});check('Player-facing copy consistently presents the airship rock drill',drillCopy.old===0&&drillCopy.drill&&drillCopy.power,JSON.stringify(drillCopy));check('Rock-drill upgrade keeps its material gate',drillCopy.blocked);

const terrain=await page.evaluate(()=>{const profiles=TERRAIN_PROFILES.map(x=>x.id),trips=[expedition.terrainProfileId];for(let i=0;i<11;i++){expedition.returnRequested=true;expedition.returnReason='manual';finishReturn();acknowledgeResult();debugDepart(1);trips.push(expedition.terrainProfileId)}return{profiles,trips}});check('Four terrain profiles exist',JSON.stringify(terrain.profiles)===JSON.stringify(['hills','spire','basin','twin']));check('Terrain varies across trips',new Set(terrain.trips).size>=3,JSON.stringify(terrain.trips));

// v0.7.3: the camera must frame the complete generated scene, including the
// crowns added after the original camera constants and the sentinel label.
// Direct generation lets this matrix cover both destinations and every terrain
// profile without depending on the route unlock state.
const fitViewports=[{name:'mobile-tall',width:390,height:844},{name:'mobile-short',width:375,height:667},{name:'desktop',width:1366,height:768},{name:'desktop-wide',width:1536,height:864}],fitSamples=[],mobileUiSamples=[];
for(const viewport of fitViewports){
  await page.setViewportSize({width:viewport.width,height:viewport.height});
  await page.waitForFunction(([width,height])=>viewW===width&&viewH===height,[viewport.width,viewport.height]);
  const samples=await page.evaluate(({viewportName})=>{const samples=[];for(const level of[1,2])for(let serial=1;serial<=24;serial++){tripSerial=serial;generateIsland(level);placeCreatures();placeTrees();setupEncounters();fitCameraToIsland();const fit=debugSceneFit(),safeWidth=fit.safe.right-fit.safe.left,safeHeight=fit.safe.bottom-fit.safe.top,sceneWidth=fit.bounds.right-fit.bounds.left,sceneHeight=fit.bounds.bottom-fit.bounds.top;const treeKinds=trees.filter(tree=>!tree.chopped&&!tree.fallen).reduce((counts,tree)=>{counts[tree.kind]=(counts[tree.kind]||0)+1;return counts},{}),required=DESTINATION_RESOURCE[level-1];samples.push({viewport:viewportName,level,serial,profile:expedition.terrainProfileId,bounds:fit.bounds,safe:fit.safe,distance:fit.distance,widthRatio:sceneWidth/safeWidth,heightRatio:sceneHeight/safeHeight,shortRatio:Math.min(sceneWidth,sceneHeight)/Math.min(safeWidth,safeHeight),inside:fit.bounds.left>=fit.safe.left-2&&fit.bounds.top>=fit.safe.top-2&&fit.bounds.right<=fit.safe.right+2&&fit.bounds.bottom<=fit.safe.bottom+2,trees:treeKinds,enemy:level===1||!!expedition.enemy?.hp,resource:cells.includes(required)})}return samples},{viewportName:viewport.name});
  fitSamples.push(...samples);
  if(viewport.width<=390){const ui=await page.evaluate(({viewportName})=>{Object.assign(expedition,{phase:'exploring',fuel:60,maxHull:3,hull:3});islandLevel=2;for(const chest of expedition.chests)chest.exposed=false;renderBase();updateHud();renderEncounter();fitCameraToIsland();const panel=document.getElementById('encounter-status'),safe=cameraSafeRect(),bounds=projectedSceneBounds();return{viewport:viewportName,panelHidden:panel.hidden,sceneInside:bounds.left>=safe.left-2&&bounds.top>=safe.top-2&&bounds.right<=safe.right+2&&bounds.bottom<=safe.bottom+2,bounds,safe}},{viewportName:viewport.name});mobileUiSamples.push(ui)}
}
const fitProfiles=new Set(fitSamples.map(sample=>sample.profile));
check('Initial camera contains every island, tree crown, and sentinel label at all target viewports',fitSamples.every(sample=>sample.inside),JSON.stringify(fitSamples.filter(sample=>!sample.inside).slice(0,8)));
const legible=sample=>sample.viewport==='mobile-short'?sample.shortRatio>=.42&&Math.max(sample.widthRatio,sample.heightRatio)>=.44:sample.shortRatio>=.62&&Math.max(sample.widthRatio,sample.heightRatio)>=.72;check('Scene remains comfortably legible instead of shrinking excessively',fitSamples.every(legible),JSON.stringify(fitSamples.map(({viewport,level,serial,profile,widthRatio,heightRatio,shortRatio})=>({viewport,level,serial,profile,widthRatio:+widthRatio.toFixed(2),heightRatio:+heightRatio.toFixed(2),shortRatio:+shortRatio.toFixed(2)})).filter(sample=>!legible(sample)).slice(0,8)));
check('Fit matrix covers all terrain profiles with the required trees, sentinel, and destination resource',fitProfiles.size===4&&fitSamples.every(sample=>sample.trees.sapling===6&&sample.trees.large===2&&sample.enemy&&sample.resource),JSON.stringify({profiles:[...fitProfiles],bad:fitSamples.filter(sample=>sample.trees.sapling!==6||sample.trees.large!==2||!sample.enemy||!sample.resource).slice(0,8)}));
check('Enemy information panel is absent during ordinary island 2 exploration',mobileUiSamples.length===2&&mobileUiSamples.every(sample=>sample.panelHidden),JSON.stringify(mobileUiSamples));
check('Mobile scene fit uses the space recovered from the removed enemy panel',mobileUiSamples.every(sample=>sample.sceneInside),JSON.stringify(mobileUiSamples.filter(sample=>!sample.sceneInside)));
const islandShape=await page.evaluate(()=>({baseDepth:ISLAND.baseDepth,depthPerLevel:ISLAND.depthPerLevel,topNoise:ISLAND.topNoise}));check('Island vertical generation is compressed from the pre-v0.7.3 constants',islandShape.baseDepth<7.6&&islandShape.depthPerLevel<1.1&&islandShape.topNoise<2.6,JSON.stringify(islandShape));

await page.setViewportSize({width:390,height:844});await page.waitForFunction(()=>viewW===390&&viewH===844);await page.evaluate(()=>{tripSerial=17;generateIsland(2);placeCreatures();placeTrees();setupEncounters();fitCameraToIsland();renderBase();markDirty();renderIslandLayer()});await page.screenshot({path:path.join(artifactDirectory,'island-fit-v073-mobile.png'),fullPage:true});
await page.setViewportSize({width:1366,height:768});await page.waitForFunction(()=>viewW===1366&&viewH===768);await page.evaluate(()=>{tripSerial=17;generateIsland(2);placeCreatures();placeTrees();setupEncounters();fitCameraToIsland();renderBase();markDirty();renderIslandLayer()});await page.screenshot({path:path.join(artifactDirectory,'island-fit-v073-desktop.png'),fullPage:true});

await fresh();const cameraBefore=await page.evaluate(()=>{debugDepart(1);return{target:[camTargetX,camTargetY,camTargetZ],focus:[camFocusX,camFocusY,camFocusZ],zoom:camera.zoom}});await page.evaluate(()=>{const center=(GX-1)/2;for(let y=0;y<GY;y++)for(let z=0;z<GZ;z++)for(let x=0;x<center-1;x++){const index=cellIndex(x,y,z);if(cells[index]){cells[index]=0;solidCount--}}rebuildSurface();focusDirty=true;markDirty()});await page.waitForTimeout(1300);const cameraFollow=await page.evaluate(()=>({target:[camTargetX,camTargetY,camTargetZ],focus:[camFocusX,camFocusY,camFocusZ]}));check('Mining centroid changes still produce smooth camera focus follow',Math.abs(cameraFollow.focus[0]-cameraBefore.focus[0])>.25&&Math.abs(cameraFollow.target[0]-cameraFollow.focus[0])<.08,JSON.stringify({before:cameraBefore,after:cameraFollow}));
await page.locator('#stage').dispatchEvent('wheel',{deltaY:-100});const manualZoom=await page.evaluate(()=>camera.zoom);check('Manual wheel zoom remains available after automatic fit',manualZoom>cameraBefore.zoom,`${cameraBefore.zoom} -> ${manualZoom}`);const savedCamera=await page.evaluate(()=>{saveGame();return{yaw:camera.yaw,pitch:camera.pitch,dist:camera.dist,zoom:camera.zoom,target:[camTargetX,camTargetY,camTargetZ]}});await page.reload();await page.waitForFunction(()=>typeof debugState==='function');const restoredCamera=await page.evaluate(()=>({yaw:camera.yaw,pitch:camera.pitch,dist:camera.dist,zoom:camera.zoom,target:[camTargetX,camTargetY,camTargetZ]})),cameraDelta=Math.max(...['yaw','pitch','dist','zoom'].map(key=>Math.abs(savedCamera[key]-restoredCamera[key])),...savedCamera.target.map((value,index)=>Math.abs(value-restoredCamera.target[index])));check('Reload restores fitted distance, manual zoom, and followed target',cameraDelta<.000001,JSON.stringify({savedCamera,restoredCamera,cameraDelta}));

await fresh();await page.evaluate(()=>{expedition.routeLevel=1;debugDepart(2)});s=await state();check('Island 2 starts sentinel on four-turn cycle',s.expedition.enemy?.attackEvery===4&&s.expedition.enemy.turnsUntilAttack===4&&s.expedition.hull===3);
const enemyVisual=await page.evaluate(()=>{const partBounds=(parts)=>{const axis=i=>[Math.min(...parts.map(part=>part[i])),Math.max(...parts.map(part=>part[i]+part[i+3]))];return[axis(0),axis(1),axis(2)]};const signature=faces=>({count:faces.length,colors:[...new Set(faces.map(face=>face.color))].sort()});const enemyParts=pose=>[...enemyBoxes(pose,false),...enemyEllipsoids(pose,false)],beetleParts=pose=>[...creatureBoxes('beetle',pose),...creatureEllipsoids('beetle',pose)];boilFrame=0;const first=buildPropFaces().filter(face=>face.entity.type==='enemy'),creature=creatures.find(entry=>entry.kind==='beetle'&&!entry.captured&&!entry.escaped),beetle=creature?buildPropFaces().filter(face=>face.entity.type==='creature'&&face.entity.id===creature.id):[];const firstParts=enemyParts(0),secondParts=enemyParts(1),normalEye=enemyEllipsoids(0,false)[3][6],warningEye=enemyEllipsoids(1,true)[3][6],normalLamp=enemyBoxes(0,false)[10][6],warningLamp=enemyBoxes(1,true)[10][6];return{first:{...signature(first),bounds:partBounds(firstParts)},beetle:{...signature(beetle),bounds:partBounds(beetleParts(0))},changed:JSON.stringify(firstParts)!==JSON.stringify(secondParts),feet:[Math.min(...firstParts.map(part=>part[1])),Math.min(...secondParts.map(part=>part[1]))],eyeChanged:JSON.stringify(normalEye)!==JSON.stringify(warningEye),lampChanged:JSON.stringify(normalLamp)!==JSON.stringify(warningLamp)}});
const extent=bounds=>bounds.map(([minimum,maximum])=>maximum-minimum),enemySize=extent(enemyVisual.first.bounds),beetleSize=extent(enemyVisual.beetle.bounds);
check('Sentinel has a dedicated mesh, palette, and larger silhouette than beetles',enemyVisual.first.count>0&&enemyVisual.beetle.count>0&&enemyVisual.first.count!==enemyVisual.beetle.count&&JSON.stringify(enemyVisual.first.colors)!==JSON.stringify(enemyVisual.beetle.colors)&&enemySize.every((size,index)=>size>beetleSize[index]),JSON.stringify(enemyVisual));
check('Sentinel two-frame motion changes articulated parts while its feet stay planted',enemyVisual.changed&&Math.abs(enemyVisual.feet[0]-enemyVisual.feet[1])<.001,JSON.stringify(enemyVisual.feet));
check('Sentinel eye and warning lamp change color before an attack',enemyVisual.eyeChanged&&enemyVisual.lampChanged,JSON.stringify(enemyVisual));
const enemyMarker=await page.evaluate(()=>{const read=()=>{const calls=[];let shape=null,fillStyle='',strokeStyle='',lineWidth=0;const context={save(){},restore(){},beginPath(){shape=null},roundRect(x,y,w,h,r){shape={x,y,w,h,r}},fill(){calls.push({kind:'fill',shape:{...shape},style:fillStyle})},stroke(){calls.push({kind:'stroke',shape:{...shape},style:strokeStyle,lineWidth})},fillText(text,x,y){calls.push({kind:'text',text,x,y})},set font(value){},set textAlign(value){},set textBaseline(value){},set fillStyle(value){fillStyle=value},set strokeStyle(value){strokeStyle=value},set lineWidth(value){lineWidth=value}};drawEnemyMarker(context);return{calls,rect:enemyMarkerHitRect&&{...enemyMarkerHitRect},visible:enemyVisibleProjection(expedition.enemy)}};markDirty();renderIslandLayer();const initial=read();expedition.enemy.hp=3;const damaged=read();expedition.enemy.hp=4;camera.yaw+=.7;updateCamBasis();updateViewDir();markDirty();renderIslandLayer();const rotated=read();expedition.enemy.turnsUntilAttack=1;boilFrame=4;const warningA=read();boilFrame=6;const warningB=read();return{initial,damaged,rotated,warningA,warningB}});
const fills=entry=>entry.calls.filter(call=>call.kind==='fill'),strokes=entry=>entry.calls.filter(call=>call.kind==='stroke'),texts=entry=>entry.calls.filter(call=>call.kind==='text').map(call=>call.text),barFills=entry=>fills(entry).filter(call=>Math.abs(call.shape.h-7)<.01),iconStroke=entry=>strokes(entry).find(call=>Math.abs(call.shape.w-28)<.01&&Math.abs(call.shape.h-28)<.01);
check('Minimal enemy HUD contains only a four-segment 48x7 HP bar and a 28px countdown icon',barFills(enemyMarker.initial).length===4&&barFills(enemyMarker.initial).every(call=>call.shape.h===7)&&Math.abs(barFills(enemyMarker.initial).at(-1).shape.x+barFills(enemyMarker.initial).at(-1).shape.w-barFills(enemyMarker.initial)[0].shape.x-48)<.01&&iconStroke(enemyMarker.initial)&&JSON.stringify(texts(enemyMarker.initial))==='["4"]'&&!enemyMarker.initial.calls.some(call=>call.text&&/古代哨戒機|耐久|攻撃まで|作業/.test(call.text)),JSON.stringify(enemyMarker.initial));
check('HP four to three changes exactly one filled segment',barFills(enemyMarker.initial).filter(call=>call.style.includes('177,83,49')).length===4&&barFills(enemyMarker.damaged).filter(call=>call.style.includes('177,83,49')).length===3,JSON.stringify({initial:barFills(enemyMarker.initial),damaged:barFills(enemyMarker.damaged)}));
check('Attack countdown 4 to 1 changes the number and warning outline pulse',texts(enemyMarker.initial)[0]==='4'&&texts(enemyMarker.warningA)[0]==='1'&&iconStroke(enemyMarker.warningA).style!==iconStroke(enemyMarker.initial).style&&iconStroke(enemyMarker.warningA).lineWidth!==iconStroke(enemyMarker.warningB).lineWidth,JSON.stringify({initial:iconStroke(enemyMarker.initial),warningA:iconStroke(enemyMarker.warningA),warningB:iconStroke(enemyMarker.warningB)}));
check('Minimal enemy HUD follows the visible enemy after camera rotation',enemyMarker.initial.rect&&enemyMarker.rotated.rect&&(enemyMarker.initial.rect.left!==enemyMarker.rotated.rect.left||enemyMarker.initial.rect.top!==enemyMarker.rotated.rect.top),JSON.stringify({initial:enemyMarker.initial.rect,rotated:enemyMarker.rotated.rect}));
const enemyVisibility=await page.evaluate(()=>{expedition.enemy.turnsUntilAttack=4;markDirty();renderIslandLayer();const read=()=>{const calls=[],context={save(){},restore(){},beginPath(){},roundRect(){},fill(){calls.push('fill')},stroke(){},fillText(){},set font(value){},set textAlign(value){},set textBaseline(value){},set fillStyle(value){},set strokeStyle(value){},set lineWidth(value){}};drawEnemyMarker(context);return{drawn:calls.length>0,rect:enemyMarkerHitRect&&{...enemyMarkerHitRect},details:!document.getElementById('enemy-details').hidden,projection:enemyVisibleProjection(expedition.enemy)}};const baseline=read(),enemyFaces=propPickFaces.filter(face=>face.entity.type==='enemy'),frontDepth=Math.min(...enemyFaces.map(face=>face.depth))-1,blocker={...enemyFaces[0],entity:{type:'tree',id:98765},depth:frontDepth,vertices:[[0,0],[viewW,0],[viewW,viewH],[0,viewH]]};openEnemyDetails();propPickFaces.push(blocker);const blocked=read();propPickFaces.pop();const restored=read();const originalVertices=enemyFaces.map(face=>face.vertices);for(const face of enemyFaces)face.vertices=face.vertices.map(([x,y])=>[x+viewW*2,y]);const offscreen=read();enemyFaces.forEach((face,index)=>face.vertices=originalVertices[index]);const minX=Math.min(...enemyFaces.flatMap(face=>face.vertices.map(vertex=>vertex[0]))),maxX=Math.max(...enemyFaces.flatMap(face=>face.vertices.map(vertex=>vertex[0]))),middle=(minX+maxX)/2,partial={...blocker,vertices:[[0,0],[middle,0],[middle,viewH],[0,viewH]]};propPickFaces.push(partial);const partlyVisible=read();propPickFaces.pop();return{baseline,blocked,restored,offscreen,partlyVisible}});
check('Enemy HUD and inspector disappear under full terrain/tree occlusion and return when visible',enemyVisibility.baseline.drawn&&enemyVisibility.baseline.rect&&enemyVisibility.blocked.drawn===false&&enemyVisibility.blocked.rect===null&&!enemyVisibility.blocked.details&&enemyVisibility.restored.drawn&&enemyVisibility.restored.rect,JSON.stringify(enemyVisibility));
check('Enemy HUD disappears offscreen but remains for partial visibility',!enemyVisibility.offscreen.drawn&&enemyVisibility.offscreen.rect===null&&enemyVisibility.partlyVisible.drawn&&enemyVisibility.partlyVisible.rect,JSON.stringify(enemyVisibility));
await page.setViewportSize({width:390,height:844});await page.waitForFunction(()=>viewW===390&&viewH===844);await page.evaluate(()=>{markDirty();renderIslandLayer()});await page.screenshot({path:path.join(artifactDirectory,'enemy-minimal-hud-v076.png'),fullPage:true});
await page.setViewportSize({width:1280,height:900});await page.evaluate(()=>{expedition.enemy.turnsUntilAttack=4;camera.yaw=-.72;updateCamBasis();updateViewDir();markDirty();renderIslandLayer()});
const enemyWorldUi=await page.evaluate(()=>{renderIslandLayer();const e=expedition.enemy,start={fuel:expedition.fuel,turns:expedition.turns,countdown:e.turnsUntilAttack,hp:e.hp},rect={...enemyMarkerHitRect},labelTap=debugTapAt((rect.left+rect.right)/2,(rect.top+rect.bottom)/2);return{start,rect,labelTap,after:{fuel:expedition.fuel,turns:expedition.turns,countdown:e.turnsUntilAttack,hp:e.hp},details:!document.getElementById('enemy-details').hidden,permanentPanel:!document.getElementById('encounter-status').hidden,attackButtons:[...document.querySelectorAll('#enemy-details button')].filter(button=>/攻撃/.test(button.textContent)).length}});
check('Tapping the world label opens details without spending fuel or advancing the enemy',enemyWorldUi.labelTap.enemyDetailsOpened&&enemyWorldUi.details&&JSON.stringify(enemyWorldUi.start)===JSON.stringify(enemyWorldUi.after),JSON.stringify(enemyWorldUi));
check('Enemy details contain no attack button and no enemy panel remains permanently visible',enemyWorldUi.attackButtons===0&&!enemyWorldUi.permanentPanel,JSON.stringify(enemyWorldUi));
const readPopover=await page.evaluate(()=>{const element=document.getElementById('enemy-details'),card=document.querySelector('.enemy-details-card'),rect=element.getBoundingClientRect(),style=getComputedStyle(element),blockers=['hud','inv','fuel-status','tools','hint','encounter-status'].map(id=>document.getElementById(id)).filter(node=>node&&!node.hidden).map(node=>{const box=node.getBoundingClientRect();return{id:node.id,left:box.left,top:box.top,right:box.right,bottom:box.bottom}}),overlaps=blockers.filter(box=>rect.left<box.right&&rect.right>box.left&&rect.top<box.bottom&&rect.bottom>box.top);return{rect:{left:rect.left,top:rect.top,right:rect.right,bottom:rect.bottom,width:rect.width,height:rect.height},background:style.backgroundColor,position:style.position,cardWidth:card.getBoundingClientRect().width,title:document.getElementById('enemy-details-title').textContent,hp:document.getElementById('enemy-details-hp').textContent,action:document.getElementById('enemy-details-action').textContent,page:document.getElementById('enemy-details-page-name').textContent,overlaps}});
check('Enemy inspector is a compact non-dimming popover with summary information',readPopover.background==='rgba(0, 0, 0, 0)'&&readPopover.position==='fixed'&&readPopover.rect.width<=196&&readPopover.rect.height<=190&&readPopover.title==='古代哨戒機'&&readPopover.hp==='HP ■■■■'&&readPopover.action.includes('あと4手'),JSON.stringify(readPopover));
const pageStateBefore=await page.evaluate(()=>({fuel:expedition.fuel,turns:expedition.turns,countdown:expedition.enemy.turnsUntilAttack,hp:expedition.enemy.hp}));
const pageNames=[];for(let i=0;i<3;i++){pageNames.push(await page.locator('#enemy-details-page-name').textContent());await page.locator('#btn-enemy-page-next').click()}await page.locator('#btn-enemy-page-prev').click();
const pageStateAfter=await page.evaluate(()=>({fuel:expedition.fuel,turns:expedition.turns,countdown:expedition.enemy.turnsUntilAttack,hp:expedition.enemy.hp}));
check('Inspector cycles through three pages without advancing the expedition',new Set(pageNames).size===3&&pageNames.every((name,index)=>name.endsWith(`${index+1}/3`))&&JSON.stringify(pageStateBefore)===JSON.stringify(pageStateAfter),JSON.stringify({pageNames,pageStateBefore,pageStateAfter}));
const cameraBeforeInspector=await page.evaluate(()=>{const rect=document.getElementById('enemy-details').getBoundingClientRect();return{yaw:camera.yaw,pitch:camera.pitch,zoom:camera.zoom,rect:{left:rect.left,top:rect.top}}});
await page.mouse.move(300,300);await page.mouse.down();await page.mouse.move(355,340,{steps:3});await page.mouse.up();
await page.evaluate(()=>{pointers.set(51,{x:250,y:300,startX:250,startY:300});pointers.set(52,{x:350,y:300,startX:350,startY:300});lastPinchDist=100;canvas.dispatchEvent(new PointerEvent('pointermove',{pointerId:52,clientX:380,clientY:300}));pointers.clear();lastPinchDist=0});await page.locator('#stage').dispatchEvent('wheel',{deltaY:-120});await page.waitForTimeout(150);
const cameraAfterInspector=await page.evaluate(()=>{const rect=document.getElementById('enemy-details').getBoundingClientRect();return{yaw:camera.yaw,pitch:camera.pitch,zoom:camera.zoom,rect:{left:rect.left,top:rect.top},visible:!document.getElementById('enemy-details').hidden,fuel:expedition.fuel,turns:expedition.turns,countdown:expedition.enemy.turnsUntilAttack}});
check('Camera drag, pinch, and wheel remain available while the inspector follows the enemy',cameraAfterInspector.visible&&cameraAfterInspector.yaw!==cameraBeforeInspector.yaw&&cameraAfterInspector.pitch!==cameraBeforeInspector.pitch&&cameraAfterInspector.zoom!==cameraBeforeInspector.zoom&&(cameraAfterInspector.rect.left!==cameraBeforeInspector.rect.left||cameraAfterInspector.rect.top!==cameraBeforeInspector.rect.top)&&cameraAfterInspector.fuel===pageStateBefore.fuel&&cameraAfterInspector.turns===pageStateBefore.turns&&cameraAfterInspector.countdown===pageStateBefore.countdown,JSON.stringify({cameraBeforeInspector,cameraAfterInspector}));
const popoverLayout=async(width,height)=>{await page.setViewportSize({width,height});await page.waitForFunction(([w,h])=>viewW===w&&viewH===h,[width,height]);await page.evaluate(()=>{if(!enemyDetailsOpen())openEnemyDetails();positionEnemyDetails()});return page.evaluate(({width,height})=>{const node=document.getElementById('enemy-details'),rect=node.getBoundingClientRect(),blockers=['hud','inv','fuel-status','tools','hint','encounter-status'].map(id=>document.getElementById(id)).filter(element=>element&&!element.hidden).map(element=>{const box=element.getBoundingClientRect();return{id:element.id,left:box.left,top:box.top,right:box.right,bottom:box.bottom}}),overlaps=blockers.filter(box=>rect.left<box.right&&rect.right>box.left&&rect.top<box.bottom&&rect.bottom>box.top);indexToXYZ(expedition.enemy.cellIndex,_xyz);cellToWorld(..._xyz,_w);const anchor=project(_w[0]+.5,_w[1]+2.15,_w[2]+.5);const distance=Math.hypot(Math.max(rect.left-anchor[0],0,anchor[0]-rect.right),Math.max(rect.top-anchor[1],0,anchor[1]-rect.bottom));return{width,height,rect:{left:rect.left,top:rect.top,right:rect.right,bottom:rect.bottom,width:rect.width,height:rect.height},overlaps,anchor,distance}},{width,height})};
const detailsTall=await popoverLayout(390,844);await page.screenshot({path:path.join(artifactDirectory,'enemy-popover-v075.png'),fullPage:true});const detailsShort=await popoverLayout(375,667);
const popoverFits=sample=>sample.rect.left>=0&&sample.rect.top>=0&&sample.rect.right<=sample.width&&sample.rect.bottom<=sample.height&&sample.rect.width<=196&&sample.rect.height<=190&&sample.overlaps.length===0&&sample.distance<=90;
check('Enemy inspector fits both mobile targets, avoids HUD controls, and stays near the enemy',popoverFits(detailsTall)&&popoverFits(detailsShort),JSON.stringify({detailsTall,detailsShort}));
await page.setViewportSize({width:390,height:844});await page.evaluate(()=>{if(!enemyDetailsOpen())openEnemyDetails();markDirty();renderIslandLayer()});const firstOutsideTap=await page.evaluate(()=>{const e=expedition.enemy,before={fuel:expedition.fuel,turns:expedition.turns,countdown:e.turnsUntilAttack,hp:e.hp};const result=debugTapAt(viewW-5,viewH/2);return{before,result,after:{fuel:expedition.fuel,turns:expedition.turns,countdown:e.turnsUntilAttack,hp:e.hp},closed:document.getElementById('enemy-details').hidden}});
check('First canvas tap outside an open inspector only closes it',firstOutsideTap.closed&&firstOutsideTap.result.enemyDetailsClosed&&JSON.stringify(firstOutsideTap.before)===JSON.stringify(firstOutsideTap.after),JSON.stringify(firstOutsideTap));
const bodyAttack=await page.evaluate(()=>{markDirty();renderIslandLayer();const face=propPickFaces.find(candidate=>{if(candidate.entity.type!=='enemy')return false;const x=candidate.vertices.reduce((sum,p)=>sum+p[0],0)/candidate.vertices.length,y=candidate.vertices.reduce((sum,p)=>sum+p[1],0)/candidate.vertices.length;return visiblePropAt(x,y)?.entity.type==='enemy'&&!(enemyMarkerHitRect&&x>=enemyMarkerHitRect.left&&x<=enemyMarkerHitRect.right&&y>=enemyMarkerHitRect.top&&y<=enemyMarkerHitRect.bottom)});if(!face)return{missing:true};const x=face.vertices.reduce((sum,p)=>sum+p[0],0)/face.vertices.length,y=face.vertices.reduce((sum,p)=>sum+p[1],0)/face.vertices.length,e=expedition.enemy,before={fuel:expedition.fuel,turns:expedition.turns,countdown:e.turnsUntilAttack,hp:e.hp},result=debugTapAt(x,y);return{before,result,after:{fuel:expedition.fuel,turns:expedition.turns,countdown:e.turnsUntilAttack,hp:e.hp},point:[x,y]}});
check('Next sentinel body tap attacks for exactly one fuel and one enemy turn',!bodyAttack.missing&&bodyAttack.result.enemyAttacked&&bodyAttack.after.fuel===bodyAttack.before.fuel-1&&bodyAttack.after.turns===bodyAttack.before.turns+1&&bodyAttack.after.countdown===bodyAttack.before.countdown-1&&bodyAttack.after.hp<bodyAttack.before.hp,JSON.stringify(bodyAttack));
const closePaths=await page.evaluate(()=>{openEnemyDetails();renderIslandLayer();const rect={...enemyMarkerHitRect};const retap=debugTapAt((rect.left+rect.right)/2,(rect.top+rect.bottom)/2);return{retap,closed:document.getElementById('enemy-details').hidden}});await page.evaluate(()=>openEnemyDetails());await page.keyboard.press('Escape');const closedByEscape=await page.locator('#enemy-details').evaluate(element=>element.hidden);await page.evaluate(()=>{openEnemyDetails();debugReturn()});const closedByReturn=await page.locator('#enemy-details').evaluate(element=>element.hidden);
check('Label re-tap, Escape, and return close the inspector',closePaths.retap.enemyDetailsClosed&&closePaths.closed&&closedByEscape&&closedByReturn,JSON.stringify({closePaths,closedByEscape,closedByReturn}));
await fresh();await page.evaluate(()=>{expedition.routeLevel=1;debugDepart(2)});
const enemyPlacement=await page.evaluate(()=>{const samples=[],profiles=new Set;for(let serial=1;serial<=48;serial++){tripSerial=serial;islandLevel=2;generateIsland(2);placeCreatures();placeTrees();setupEncounters();profiles.add(expedition.terrainProfileId);const enemy=expedition.enemy;if(!enemy){samples.push({profile:expedition.terrainProfileId,missing:true});continue}indexToXYZ(enemy.cellIndex,_xyz);const xyz=[..._xyz],solid=!!cells[enemy.cellIndex],air=!cellAt(xyz[0],xyz[1]+1,xyz[2]),inside=xyz[0]>=0&&xyz[0]<GX&&xyz[1]>=0&&xyz[1]<GY&&xyz[2]>=0&&xyz[2]<GZ;const occupied=[...trees.filter(t=>!t.chopped&&!t.fallen).map(t=>t.cellIndex),...creatures.filter(c=>!c.captured&&!c.escaped).map(c=>c.cellIndex),...expedition.chests.map(c=>c.cellIndex)];const collision=occupied.includes(enemy.cellIndex);const bottoms=[];const originalBox=addPropBox,originalOval=addPropEllipsoid;addPropBox=function(faces,entity,origin,box,...rest){if(entity.type==='enemy')bottoms.push(origin[1]+box[1]*CREATURE_MESH_SCALE);return originalBox(faces,entity,origin,box,...rest)};addPropEllipsoid=function(faces,entity,origin,oval,...rest){if(entity.type==='enemy')bottoms.push(origin[1]+oval[1]*CREATURE_MESH_SCALE);return originalOval(faces,entity,origin,oval,...rest)};buildPropFaces();addPropBox=originalBox;addPropEllipsoid=originalOval;const meshMin=Math.min(...bottoms);cellToWorld(...xyz,_w);samples.push({profile:expedition.terrainProfileId,solid,air,inside,collision,mesh:bottoms.length>0,footDelta:Math.abs(meshMin-(_w[1]+1))})}return{profiles:[...profiles],samples}});
check('Island 2 sentinel stands safely on all four terrain profiles across trips',enemyPlacement.profiles.length===4&&enemyPlacement.samples.every(sample=>!sample.missing&&sample.solid&&sample.air&&sample.inside&&!sample.collision),JSON.stringify(enemyPlacement));
check('Sentinel mesh feet meet the supporting block top',enemyPlacement.samples.every(sample=>sample.mesh&&sample.footDelta<.001),JSON.stringify(enemyPlacement.samples.map(sample=>sample.footDelta)));
const enemyRelocation=await page.evaluate(()=>{tripSerial=73;islandLevel=2;generateIsland(2);placeCreatures();placeTrees();setupEncounters();const enemy=expedition.enemy,old=enemy?.cellIndex;if(!enemy)return{missing:true};cells[old]=0;solidCount--;relocateEnemy();const retreated=enemy.hp===0;const moved=!retreated&&enemy.cellIndex!==old&&enemyGroundIsSafe(enemy.cellIndex,1);const hull=expedition.hull,countdown=enemy.turnsUntilAttack;expedition.fuel=Math.max(1,expedition.fuel);beginAction();completeAction();return{retreated,moved,stopped:!retreated||expedition.hull===hull&&enemy.turnsUntilAttack===countdown}});check('Sentinel relocates after losing footing or retreats and stops attacking',!enemyRelocation.missing&&(enemyRelocation.moved||enemyRelocation.retreated)&&enemyRelocation.stopped,JSON.stringify(enemyRelocation));
await fresh();await page.evaluate(()=>{expedition.routeLevel=1;debugDepart(2)});
const turns=await page.evaluate(()=>{const e=expedition.enemy,start=e.turnsUntilAttack;camera.yaw+=.5;updateCamBasis();updateViewDir();renderIslandLayer();const free=e.turnsUntilAttack===start&&expedition.turns===0;for(let i=0;i<3;i++){beginAction();completeAction()}const calls=[],context={save(){},restore(){},beginPath(){},roundRect(){},fill(){},stroke(){},fillText(text){calls.push(text)},set font(value){},set textAlign(value){},set textBaseline(value){},set fillStyle(value){},set strokeStyle(value){},set lineWidth(value){}};boilFrame=4;drawEnemyMarker(context);const warning=e.turnsUntilAttack===1&&calls.length===1&&calls[0]==='1',h=expedition.hull;beginAction();completeAction();return{free,warning,attacked:expedition.hull===h-1,turns:expedition.turns}});check('Camera movement is zero turns',turns.free);check('Sentinel warns before attack with countdown icon 1',turns.warning);check('Sentinel attacks on fourth action',turns.attacked&&turns.turns===4);

await fresh();const chain=await page.evaluate(()=>{expedition.routeLevel=1;debugDepart(2);const e=expedition.enemy;cells.fill(0);damage.fill(0);creatures.length=0;trees.length=0;pendingBreaks.length=0;for(let x=2;x<6;x++)cells[cellIndex(x,2,2)]=M_COPPER;cells[cellIndex(7,2,2)]=M_STONE;solidCount=5;e.cellIndex=cellIndex(7,2,2);player.pickaxe=5;player.chain=1;expedition.fuel=20;e.turnsUntilAttack=4;rebuildSurface();mineAt(2,2,2,195,422);const during={threat:e.turnsUntilAttack,pending:pendingBreaks.length,turns:expedition.turns};nowSeconds+=100;processPendingBreaks();return{during,after:e.turnsUntilAttack,turns:expedition.turns}});check('Chain counts as one enemy turn',chain.during.pending>0&&chain.during.threat===4&&chain.after===3&&chain.turns===1,JSON.stringify(chain));

await fresh();const chest=await page.evaluate(()=>{expedition.routeLevel=1;debugDepart(2);const generated=expedition.chests.length;if(!generated)return{generated};const c=expedition.chests[0];indexToXYZ(c.cellIndex,_xyz);cells[cellIndex(_xyz[0]+1,_xyz[1],_xyz[2])]=0;updateChestExposure();const exposed=c.exposed,panel=!document.getElementById('encounter-status').hidden,title=document.getElementById('encounter-title').textContent,fuel=expedition.fuel,first=debugOpenChest(),panelAfter=document.getElementById('encounter-status').hidden,unlocked=player.workshopUnlocked,blueprints=player.blueprints,second=debugOpenChest();return{generated,exposed,panel,title,first,second,panelAfter,opened:c.opened,unlocked,blueprints,fuel,after:expedition.fuel}});check('Locked-workshop island 2 generates at least one real chest',chest.generated>=1);check('Only an exposed chest opens the contextual encounter panel',chest.exposed&&chest.panel&&chest.title==='埋没宝箱'&&chest.panelAfter,JSON.stringify(chest));check('Exposed chest costs one fuel and unlocks workshop',chest.exposed&&chest.first&&chest.opened&&chest.unlocked&&chest.blueprints===1&&chest.after===chest.fuel-1);check('Chest cannot be collected twice',!chest.second&&chest.blueprints===1);

await fresh();const defeat=await page.evaluate(()=>{expedition.routeLevel=1;debugDepart(2);openEnemyDetails();player.power=10;const n=player.gears.length,hit=debugAttackEnemy(),faces=buildPropFaces().filter(face=>face.entity.type==='enemy').length,calls=[],context={save(){},restore(){},beginPath(){},roundRect(){},fill(){},stroke(){},fillText(text){calls.push(text)},measureText(){return{width:10}},set font(value){},set textAlign(value){},set textBaseline(value){},set fillStyle(value){},set strokeStyle(value){},set lineWidth(value){}};drawEnemyMarker(context);return{hit,dead:expedition.enemy.hp===0,drop:player.gears.length===n+1,ids:expedition.gearIds.length,faces,labels:calls.length,detailsClosed:document.getElementById('enemy-details').hidden,markerCleared:enemyMarkerHitRect===null}});check('Sentinel defeat closes details and removes its mesh and label',defeat.hit&&defeat.dead&&defeat.drop&&defeat.ids===1&&defeat.faces===0&&defeat.labels===0&&defeat.detailsClosed&&defeat.markerCleared,JSON.stringify(defeat));
await fresh();const retreat=await page.evaluate(()=>{expedition.routeLevel=1;debugDepart(2);openEnemyDetails();cells.fill(0);solidCount=0;relocateEnemy();drawEnemyMarker({save(){},restore(){},beginPath(){},roundRect(){},fill(){},stroke(){},fillText(){},measureText(){return{width:10}},set font(value){},set textAlign(value){},set textBaseline(value){},set fillStyle(value){},set strokeStyle(value){},set lineWidth(value){}});return{retreated:expedition.enemy.hp===0,detailsClosed:document.getElementById('enemy-details').hidden,markerCleared:enemyMarkerHitRect===null}});check('Sentinel retreat closes details and removes its world label',retreat.retreated&&retreat.detailsClosed&&retreat.markerCleared,JSON.stringify(retreat));
await fresh();const creatureRegression=await page.evaluate(()=>{debugDepart(1);const creature=creatures.find(entry=>!entry.captured&&!entry.escaped);if(!creature)return{missing:true};const facesBefore=buildPropFaces().filter(face=>face.entity.type==='creature'&&face.entity.id===creature.id).length,fuel=expedition.fuel,originalProjection=creatureProjection;creatureProjection=entry=>entry.id===creature.id?{id:entry.id,x:viewW/2,y:viewH/2,depth:1}:originalProjection(entry);const captured=debugCapture(creature.id);creatureProjection=originalProjection;const facesAfter=buildPropFaces().filter(face=>face.entity.type==='creature'&&face.entity.id===creature.id).length;return{facesBefore,fuel,captured,facesAfter,fuelAfter:expedition.fuel,marked:creature.captured}});check('Ordinary creature mesh and capture behavior remain intact',!creatureRegression.missing&&creatureRegression.facesBefore>0&&creatureRegression.captured&&creatureRegression.facesAfter===0&&creatureRegression.fuelAfter===creatureRegression.fuel-1&&creatureRegression.marked,JSON.stringify(creatureRegression));
await fresh();const hull=await page.evaluate(()=>{expedition.routeLevel=1;debugDepart(2);expedition.hull=1;expedition.enemy.turnsUntilAttack=1;debugAttackEnemy();return{phase:expedition.phase,reason:expedition.returnReason,hull:expedition.hull}});check('Hull zero triggers result return',hull.phase==='result'&&hull.reason==='hull'&&hull.hull===0);

await fresh();const fuel=await page.evaluate(()=>{debugDepart(1);cells.fill(0);damage.fill(0);pendingBreaks.length=0;creatures.length=0;trees.length=0;cells[cellIndex(2,2,2)]=M_COPPER;cells[cellIndex(7,2,2)]=M_STONE;solidCount=2;rebuildSurface();expedition.fuel=1;player.pickaxe=5;player.power=20;player.range=0;player.chain=0;mineAt(2,2,2,195,422);return{phase:expedition.phase,requested:expedition.returnRequested,fuel:expedition.fuel,text:document.getElementById('fuel-notice-message').textContent,visible:!document.getElementById('fuel-notice').hidden}});check('Fuel depletion pauses at return message',fuel.phase==='exploring'&&fuel.requested&&fuel.fuel===0&&fuel.visible&&fuel.text==='燃料がなくなった。帰還しよう。');await page.evaluate(()=>debugAcknowledgeFuelNotice());check('Fuel notice proceeds to result',(await state()).expedition.phase==='result');
check('No runtime errors',errors.length===0,JSON.stringify(errors));
}finally{await browser.close()}if(fail.length){console.error(`\n${fail.length} failed: ${fail.join(', ')}`);process.exitCode=1}else console.log('\nAll voxel-mine v0.7 acceptance checks passed.');
