import {createRequire} from'node:module';import {mkdir} from'node:fs/promises';import path from'node:path';import{fileURLToPath,pathToFileURL}from'node:url';
const here=path.dirname(fileURLToPath(import.meta.url)),req=createRequire(import.meta.url);let pw;for(const c of[process.env.PLAYWRIGHT_MODULE_PATH,'playwright'].filter(Boolean))try{pw=req(c);break}catch{}if(!pw)throw Error('Set PLAYWRIGHT_MODULE_PATH');
const browser=await pw.chromium.launch(process.env.PLAYWRIGHT_EXECUTABLE_PATH?{executablePath:process.env.PLAYWRIGHT_EXECUTABLE_PATH}:{}),page=await browser.newPage({viewport:{width:390,height:844}}),fail=[],errors=[];
page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});page.on('requestfailed',r=>errors.push(r.url()));page.on('dialog',d=>d.accept());
const check=(n,v,d='')=>{console.log(`${v?'PASS':'FAIL'} ${n} ${d}`);if(!v)fail.push(n)},url=pathToFileURL(path.join(here,'index.html')).href+'?seed=777&fresh=v07',state=()=>page.evaluate(()=>debugState());
const artifactDirectory=path.resolve(process.env.VOXEL_ARTIFACT_DIR||path.join(here,'../../artifacts/voxel-mine'));await mkdir(artifactDirectory,{recursive:true});
async function fresh(){await page.goto(url);await page.waitForFunction(()=>typeof debugState==='function');await page.evaluate(()=>resetGame())}
try{
await fresh();let s=await state();check('Initial gear capacity 6, empty loadout, workshop locked',s.player.gearCapacity===6&&!s.player.gears.length&&!s.player.equippedGearIds.length&&!s.player.workshopUnlocked);
await page.evaluate(()=>{player.gears.push({id:'x',name:'x',trait:'fuel',weight:2});player.workshopUnlocked=true;debugSave();resetGame()});s=await state();check('Debug reset clears v0.7 progression',!s.player.gears.length&&!s.player.workshopUnlocked&&s.player.gearCapacity===6);
await page.evaluate(()=>localStorage.setItem(saveKey(),JSON.stringify({version:7,worldSeed,player:{coins:999},island:{}})));await page.reload();await page.waitForFunction(()=>typeof debugState==='function');s=await state();check('Old save schema initializes fresh schema 8',s.player.coins===0&&JSON.parse(await page.evaluate(()=>localStorage.getItem(saveKey()))).version===8);

const loot=await page.evaluate(()=>{debugDepart(1);const a=createTreasure('same'),b=createTreasure('same'),many=Array.from({length:12},(_,i)=>createTreasure('v'+i)),kept=gainTreasure('kept');debugSave();return{a,b,many,kept}});
check('Treasure individual is deterministic with name/value/flavor',JSON.stringify(loot.a)===JSON.stringify(loot.b)&&loot.a.name&&loot.a.value>0&&loot.a.flavor);check('Treasure sources produce varied individuals',new Set(loot.many.map(x=>x.name+'|'+x.value+'|'+x.flavor)).size>=4);await page.reload();check('Treasure individual persists on reload',await page.evaluate(x=>JSON.stringify(player.treasures.find(y=>y.id===x.id))===JSON.stringify(x),loot.kept));

await page.evaluate(()=>{expedition.returnRequested=true;expedition.returnReason='manual';finishReturn();acknowledgeResult()});const gear=await page.evaluate(()=>{player.gears=[{id:'p',name:'P',trait:'power',weight:2},{id:'f',name:'F',trait:'fuel',weight:2},{id:'c',name:'C',trait:'chain',weight:2},{id:'e',name:'E',trait:'appraisal',weight:1}];player.equippedGearIds=[];const base=[hitPower(),fuelCapacity(),chainCount()],toggles=['p','f','c','e'].map(debugToggleGear),equipped={ids:[...player.equippedGearIds],weight:equippedWeight(),stats:[hitPower(),fuelCapacity(),chainCount()]};debugDepart(1);const before=JSON.stringify(player.equippedGearIds),outside=debugToggleGear('p');return{base,toggles,equipped,outside,unchanged:before===JSON.stringify(player.equippedGearIds)}});
check('Gear enforces weight 6 and maximum 3',gear.toggles.slice(0,3).every(Boolean)&&!gear.toggles[3]&&gear.equipped.weight===6&&gear.equipped.ids.length===3);check('Equipped gear effects apply',gear.equipped.stats[0]===gear.base[0]+1&&gear.equipped.stats[1]===gear.base[1]+6&&gear.equipped.stats[2]===gear.base[2]+2);check('Gear changes are port-only',!gear.outside&&gear.unchanged);

await fresh();const drillCopy=await page.evaluate(()=>{const text=document.body.innerText;return{old:(text.match(/つるはし/g)||[]).length,drill:text.includes('船外削岩機'),power:text.includes('削岩出力'),blocked:!debugCraft('pickaxe')}});check('Player-facing copy consistently presents the airship rock drill',drillCopy.old===0&&drillCopy.drill&&drillCopy.power,JSON.stringify(drillCopy));check('Rock-drill upgrade keeps its material gate',drillCopy.blocked);

const terrain=await page.evaluate(()=>{const profiles=TERRAIN_PROFILES.map(x=>x.id),trips=[expedition.terrainProfileId];for(let i=0;i<11;i++){expedition.returnRequested=true;expedition.returnReason='manual';finishReturn();acknowledgeResult();debugDepart(1);trips.push(expedition.terrainProfileId)}return{profiles,trips}});check('Four terrain profiles exist',JSON.stringify(terrain.profiles)===JSON.stringify(['hills','spire','basin','twin']));check('Terrain varies across trips',new Set(terrain.trips).size>=3,JSON.stringify(terrain.trips));

await fresh();await page.evaluate(()=>{expedition.routeLevel=1;debugDepart(2)});s=await state();check('Island 2 starts sentinel on four-turn cycle',s.expedition.enemy?.attackEvery===4&&s.expedition.enemy.turnsUntilAttack===4&&s.expedition.hull===3);
const enemyVisual=await page.evaluate(()=>{const partBounds=(parts)=>{const axis=i=>[Math.min(...parts.map(part=>part[i])),Math.max(...parts.map(part=>part[i]+part[i+3]))];return[axis(0),axis(1),axis(2)]};const signature=faces=>({count:faces.length,colors:[...new Set(faces.map(face=>face.color))].sort()});const enemyParts=pose=>[...enemyBoxes(pose,false),...enemyEllipsoids(pose,false)],beetleParts=pose=>[...creatureBoxes('beetle',pose),...creatureEllipsoids('beetle',pose)];boilFrame=0;const first=buildPropFaces().filter(face=>face.entity.type==='enemy'),creature=creatures.find(entry=>entry.kind==='beetle'&&!entry.captured&&!entry.escaped),beetle=creature?buildPropFaces().filter(face=>face.entity.type==='creature'&&face.entity.id===creature.id):[];const firstParts=enemyParts(0),secondParts=enemyParts(1),normalEye=enemyEllipsoids(0,false)[3][6],warningEye=enemyEllipsoids(1,true)[3][6],normalLamp=enemyBoxes(0,false)[10][6],warningLamp=enemyBoxes(1,true)[10][6];return{first:{...signature(first),bounds:partBounds(firstParts)},beetle:{...signature(beetle),bounds:partBounds(beetleParts(0))},changed:JSON.stringify(firstParts)!==JSON.stringify(secondParts),feet:[Math.min(...firstParts.map(part=>part[1])),Math.min(...secondParts.map(part=>part[1]))],eyeChanged:JSON.stringify(normalEye)!==JSON.stringify(warningEye),lampChanged:JSON.stringify(normalLamp)!==JSON.stringify(warningLamp)}});
const extent=bounds=>bounds.map(([minimum,maximum])=>maximum-minimum),enemySize=extent(enemyVisual.first.bounds),beetleSize=extent(enemyVisual.beetle.bounds);
check('Sentinel has a dedicated mesh, palette, and larger silhouette than beetles',enemyVisual.first.count>0&&enemyVisual.beetle.count>0&&enemyVisual.first.count!==enemyVisual.beetle.count&&JSON.stringify(enemyVisual.first.colors)!==JSON.stringify(enemyVisual.beetle.colors)&&enemySize.every((size,index)=>size>beetleSize[index]),JSON.stringify(enemyVisual));
check('Sentinel two-frame motion changes articulated parts while its feet stay planted',enemyVisual.changed&&Math.abs(enemyVisual.feet[0]-enemyVisual.feet[1])<.001,JSON.stringify(enemyVisual.feet));
check('Sentinel eye and warning lamp change color before an attack',enemyVisual.eyeChanged&&enemyVisual.lampChanged,JSON.stringify(enemyVisual));
const enemyMarker=await page.evaluate(()=>{const read=()=>{const calls=[];const context={save(){},restore(){},beginPath(){},roundRect(x,y,w,h){calls.push({box:[x,y,w,h]})},fill(){},stroke(){},fillText(text,x,y){calls.push({text,x,y})},measureText(text){return{width:text.length*8}},set font(value){},set textAlign(value){},set textBaseline(value){},set fillStyle(value){},set strokeStyle(value){},set lineWidth(value){}};drawEnemyMarker(context);return calls};const expected=()=>{indexToXYZ(expedition.enemy.cellIndex,_xyz);cellToWorld(..._xyz,_w);return project(_w[0]+.5,_w[1]+4.05,_w[2]+.5).slice(0,2)};const first={calls:read(),expected:expected()};camera.yaw+=.7;updateCamBasis();updateViewDir();const rotated={calls:read(),expected:expected()};expedition.enemy.turnsUntilAttack=1;boilFrame=4;const warning=read();return{first,rotated,warning}});
const markerText=entry=>entry.calls.find(call=>call.text),near=(left,right)=>Math.hypot(left[0]-right[0],left[1]-right[1])<.01;
check('Sentinel overhead label names the enemy and uses normal/warning symbols',markerText(enemyMarker.first)?.text==='◆ 古代哨戒機'&&enemyMarker.warning.find(call=>call.text)?.text==='⚠ 古代哨戒機',JSON.stringify(enemyMarker));
check('Sentinel label follows its projected position after camera rotation',near([markerText(enemyMarker.first).x,markerText(enemyMarker.first).y-.5],enemyMarker.first.expected)&&near([markerText(enemyMarker.rotated).x,markerText(enemyMarker.rotated).y-.5],enemyMarker.rotated.expected)&&Math.hypot(...enemyMarker.first.expected.map((value,index)=>value-enemyMarker.rotated.expected[index]))>1,JSON.stringify(enemyMarker));
await page.setViewportSize({width:1280,height:900});await page.evaluate(()=>{expedition.enemy.turnsUntilAttack=4;camera.yaw=-.72;updateCamBasis();updateViewDir();markDirty();renderIslandLayer()});await page.screenshot({path:path.join(artifactDirectory,'sentinel-v072.png'),fullPage:true});
const enemyPlacement=await page.evaluate(()=>{const samples=[],profiles=new Set;for(let serial=1;serial<=48;serial++){tripSerial=serial;islandLevel=2;generateIsland(2);placeCreatures();placeTrees();setupEncounters();profiles.add(expedition.terrainProfileId);const enemy=expedition.enemy;if(!enemy){samples.push({profile:expedition.terrainProfileId,missing:true});continue}indexToXYZ(enemy.cellIndex,_xyz);const xyz=[..._xyz],solid=!!cells[enemy.cellIndex],air=!cellAt(xyz[0],xyz[1]+1,xyz[2]),inside=xyz[0]>=0&&xyz[0]<GX&&xyz[1]>=0&&xyz[1]<GY&&xyz[2]>=0&&xyz[2]<GZ;const occupied=[...trees.filter(t=>!t.chopped&&!t.fallen).map(t=>t.cellIndex),...creatures.filter(c=>!c.captured&&!c.escaped).map(c=>c.cellIndex),...expedition.chests.map(c=>c.cellIndex)];const collision=occupied.includes(enemy.cellIndex);const bottoms=[];const originalBox=addPropBox,originalOval=addPropEllipsoid;addPropBox=function(faces,entity,origin,box,...rest){if(entity.type==='enemy')bottoms.push(origin[1]+box[1]*CREATURE_MESH_SCALE);return originalBox(faces,entity,origin,box,...rest)};addPropEllipsoid=function(faces,entity,origin,oval,...rest){if(entity.type==='enemy')bottoms.push(origin[1]+oval[1]*CREATURE_MESH_SCALE);return originalOval(faces,entity,origin,oval,...rest)};buildPropFaces();addPropBox=originalBox;addPropEllipsoid=originalOval;const meshMin=Math.min(...bottoms);cellToWorld(...xyz,_w);samples.push({profile:expedition.terrainProfileId,solid,air,inside,collision,mesh:bottoms.length>0,footDelta:Math.abs(meshMin-(_w[1]+1))})}return{profiles:[...profiles],samples}});
check('Island 2 sentinel stands safely on all four terrain profiles across trips',enemyPlacement.profiles.length===4&&enemyPlacement.samples.every(sample=>!sample.missing&&sample.solid&&sample.air&&sample.inside&&!sample.collision),JSON.stringify(enemyPlacement));
check('Sentinel mesh feet meet the supporting block top',enemyPlacement.samples.every(sample=>sample.mesh&&sample.footDelta<.001),JSON.stringify(enemyPlacement.samples.map(sample=>sample.footDelta)));
const enemyRelocation=await page.evaluate(()=>{tripSerial=73;islandLevel=2;generateIsland(2);placeCreatures();placeTrees();setupEncounters();const enemy=expedition.enemy,old=enemy?.cellIndex;if(!enemy)return{missing:true};cells[old]=0;solidCount--;relocateEnemy();const retreated=enemy.hp===0;const moved=!retreated&&enemy.cellIndex!==old&&enemyGroundIsSafe(enemy.cellIndex,1);const hull=expedition.hull,countdown=enemy.turnsUntilAttack;expedition.fuel=Math.max(1,expedition.fuel);beginAction();completeAction();return{retreated,moved,stopped:!retreated||expedition.hull===hull&&enemy.turnsUntilAttack===countdown}});check('Sentinel relocates after losing footing or retreats and stops attacking',!enemyRelocation.missing&&(enemyRelocation.moved||enemyRelocation.retreated)&&enemyRelocation.stopped,JSON.stringify(enemyRelocation));
await fresh();await page.evaluate(()=>{expedition.routeLevel=1;debugDepart(2)});
const turns=await page.evaluate(()=>{const e=expedition.enemy,start=e.turnsUntilAttack;camera.yaw+=.5;updateCamBasis();updateViewDir();renderIslandLayer();const free=e.turnsUntilAttack===start&&expedition.turns===0;for(let i=0;i<3;i++){beginAction();completeAction()}renderEncounter();const warning=e.turnsUntilAttack===1&&document.getElementById('encounter-text').textContent.includes('警告'),h=expedition.hull;beginAction();completeAction();return{free,warning,attacked:expedition.hull===h-1,turns:expedition.turns}});check('Camera movement is zero turns',turns.free);check('Sentinel warns before attack',turns.warning);check('Sentinel attacks on fourth action',turns.attacked&&turns.turns===4);

await fresh();const chain=await page.evaluate(()=>{expedition.routeLevel=1;debugDepart(2);const e=expedition.enemy;cells.fill(0);damage.fill(0);creatures.length=0;trees.length=0;pendingBreaks.length=0;for(let x=2;x<6;x++)cells[cellIndex(x,2,2)]=M_COPPER;cells[cellIndex(7,2,2)]=M_STONE;solidCount=5;e.cellIndex=cellIndex(7,2,2);player.pickaxe=5;player.chain=1;expedition.fuel=20;e.turnsUntilAttack=4;rebuildSurface();mineAt(2,2,2,195,422);const during={threat:e.turnsUntilAttack,pending:pendingBreaks.length,turns:expedition.turns};nowSeconds+=100;processPendingBreaks();return{during,after:e.turnsUntilAttack,turns:expedition.turns}});check('Chain counts as one enemy turn',chain.during.pending>0&&chain.during.threat===4&&chain.after===3&&chain.turns===1,JSON.stringify(chain));

await fresh();const chest=await page.evaluate(()=>{expedition.routeLevel=1;debugDepart(2);const generated=expedition.chests.length;if(!generated)return{generated};const c=expedition.chests[0];indexToXYZ(c.cellIndex,_xyz);cells[cellIndex(_xyz[0]+1,_xyz[1],_xyz[2])]=0;updateChestExposure();const exposed=c.exposed,fuel=expedition.fuel,first=debugOpenChest(),unlocked=player.workshopUnlocked,blueprints=player.blueprints,second=debugOpenChest();return{generated,exposed,first,second,opened:c.opened,unlocked,blueprints,fuel,after:expedition.fuel}});check('Locked-workshop island 2 generates at least one real chest',chest.generated>=1);check('Exposed chest costs one fuel and unlocks workshop',chest.exposed&&chest.first&&chest.opened&&chest.unlocked&&chest.blueprints===1&&chest.after===chest.fuel-1);check('Chest cannot be collected twice',!chest.second&&chest.blueprints===1);

await fresh();const defeat=await page.evaluate(()=>{expedition.routeLevel=1;debugDepart(2);player.power=10;const n=player.gears.length,hit=debugAttackEnemy(),faces=buildPropFaces().filter(face=>face.entity.type==='enemy').length,calls=[],context={save(){},restore(){},beginPath(){},roundRect(){},fill(){},stroke(){},fillText(text){calls.push(text)},measureText(){return{width:10}},set font(value){},set textAlign(value){},set textBaseline(value){},set fillStyle(value){},set strokeStyle(value){},set lineWidth(value){}};drawEnemyMarker(context);return{hit,dead:expedition.enemy.hp===0,drop:player.gears.length===n+1,ids:expedition.gearIds.length,faces,labels:calls.length}});check('Sentinel defeat drops gear and removes its mesh and label',defeat.hit&&defeat.dead&&defeat.drop&&defeat.ids===1&&defeat.faces===0&&defeat.labels===0,JSON.stringify(defeat));
await fresh();const creatureRegression=await page.evaluate(()=>{expedition.routeLevel=1;debugDepart(2);const creature=creatures.find(entry=>!entry.captured&&!entry.escaped);if(!creature)return{missing:true};const facesBefore=buildPropFaces().filter(face=>face.entity.type==='creature'&&face.entity.id===creature.id).length,fuel=expedition.fuel,captured=debugCapture(creature.id),facesAfter=buildPropFaces().filter(face=>face.entity.type==='creature'&&face.entity.id===creature.id).length;return{facesBefore,fuel,captured,facesAfter,fuelAfter:expedition.fuel,marked:creature.captured}});check('Ordinary creature mesh and capture behavior remain intact',!creatureRegression.missing&&creatureRegression.facesBefore>0&&creatureRegression.captured&&creatureRegression.facesAfter===0&&creatureRegression.fuelAfter===creatureRegression.fuel-1&&creatureRegression.marked,JSON.stringify(creatureRegression));
await fresh();const hull=await page.evaluate(()=>{expedition.routeLevel=1;debugDepart(2);expedition.hull=1;expedition.enemy.turnsUntilAttack=1;debugAttackEnemy();return{phase:expedition.phase,reason:expedition.returnReason,hull:expedition.hull}});check('Hull zero triggers result return',hull.phase==='result'&&hull.reason==='hull'&&hull.hull===0);

await fresh();const fuel=await page.evaluate(()=>{debugDepart(1);cells.fill(0);damage.fill(0);pendingBreaks.length=0;creatures.length=0;trees.length=0;cells[cellIndex(2,2,2)]=M_COPPER;cells[cellIndex(7,2,2)]=M_STONE;solidCount=2;rebuildSurface();expedition.fuel=1;player.pickaxe=5;player.power=20;player.range=0;player.chain=0;mineAt(2,2,2,195,422);return{phase:expedition.phase,requested:expedition.returnRequested,fuel:expedition.fuel,text:document.getElementById('fuel-notice-message').textContent,visible:!document.getElementById('fuel-notice').hidden}});check('Fuel depletion pauses at return message',fuel.phase==='exploring'&&fuel.requested&&fuel.fuel===0&&fuel.visible&&fuel.text==='燃料がなくなった。帰還しよう。');await page.evaluate(()=>debugAcknowledgeFuelNotice());check('Fuel notice proceeds to result',(await state()).expedition.phase==='result');
check('No runtime errors',errors.length===0,JSON.stringify(errors));
}finally{await browser.close()}if(fail.length){console.error(`\n${fail.length} failed: ${fail.join(', ')}`);process.exitCode=1}else console.log('\nAll voxel-mine v0.7 acceptance checks passed.');
