import {createRequire} from'node:module';import {mkdir} from'node:fs/promises';import path from'node:path';import{fileURLToPath,pathToFileURL}from'node:url';
const here=path.dirname(fileURLToPath(import.meta.url)),req=createRequire(import.meta.url);let pw;for(const c of[process.env.PLAYWRIGHT_MODULE_PATH,'playwright'].filter(Boolean))try{pw=req(c);break}catch{}if(!pw)throw Error('Set PLAYWRIGHT_MODULE_PATH');
const browser=await pw.chromium.launch(process.env.PLAYWRIGHT_EXECUTABLE_PATH?{executablePath:process.env.PLAYWRIGHT_EXECUTABLE_PATH}:{}),page=await browser.newPage({viewport:{width:390,height:844}}),fail=[],errors=[];
page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});page.on('requestfailed',r=>errors.push(r.url()));page.on('dialog',d=>d.accept());
const check=(n,v,d='')=>{console.log(`${v?'PASS':'FAIL'} ${n} ${d}`);if(!v)fail.push(n)},url=pathToFileURL(path.join(here,'index.html')).href+'?seed=777&fresh=v07',state=()=>page.evaluate(()=>debugState());
const artifactDirectory=path.resolve(process.env.VOXEL_ARTIFACT_DIR||path.join(here,'../../artifacts/voxel-mine'));await mkdir(artifactDirectory,{recursive:true});
async function fresh(){await page.goto(url);await page.waitForFunction(()=>typeof debugState==='function');await page.evaluate(()=>resetGame())}
try{
await fresh();let s=await state();check('Initial gear capacity 6, empty loadout, workshop locked',s.player.gearCapacity===6&&!s.player.gears.length&&!s.player.equippedGearIds.length&&!s.player.workshopUnlocked);
await page.evaluate(()=>{player.gears.push({id:'x',name:'x',trait:'fuel',weight:2});player.workshopUnlocked=true;debugSave();resetGame()});s=await state();check('Debug reset clears v0.7 progression',!s.player.gears.length&&!s.player.workshopUnlocked&&s.player.gearCapacity===6);
await page.evaluate(()=>localStorage.setItem(saveKey(),JSON.stringify({version:7,worldSeed,player:{coins:999},island:{}})));await page.reload();await page.waitForFunction(()=>typeof debugState==='function');s=await state();check('Old save schema initializes fresh schema 8',s.player.coins===0&&JSON.parse(await page.evaluate(()=>localStorage.getItem(saveKey()))).version===8);

const loot=await page.evaluate(()=>{debugDepart(1);const a=createTreasure('same'),b=createTreasure('same'),many=Array.from({length:12},(_,i)=>createTreasure('v'+i)),kept=gainTreasure('kept');debugSave();return{a,b,many,kept}});
check('Treasure individual is deterministic with name/value/flavor',JSON.stringify(loot.a)===JSON.stringify(loot.b)&&loot.a.name&&loot.a.value>0&&loot.a.flavor);check('Treasure sources produce varied individuals',new Set(loot.many.map(x=>x.name+'|'+x.value+'|'+x.flavor)).size>=4);await page.reload();check('Treasure individual persists on reload',await page.evaluate(x=>JSON.stringify(player.treasures.find(y=>y.id===x.id))===JSON.stringify(x),loot.kept));

await page.evaluate(()=>{expedition.returnRequested=true;expedition.returnReason='manual';finishReturn();acknowledgeResult()});const gear=await page.evaluate(()=>{player.gears=[{id:'p',name:'P',trait:'power',weight:2},{id:'f',name:'F',trait:'fuel',weight:2},{id:'c',name:'C',trait:'chain',weight:2},{id:'e',name:'E',trait:'appraisal',weight:1}];player.equippedGearIds=[];const base=[hitPower(),fuelCapacity(),chainCount()],toggles=['p','f','c','e'].map(debugToggleGear),equipped={ids:[...player.equippedGearIds],weight:equippedWeight(),stats:[hitPower(),fuelCapacity(),chainCount()]};debugDepart(1);const before=JSON.stringify(player.equippedGearIds),outside=debugToggleGear('p');return{base,toggles,equipped,outside,unchanged:before===JSON.stringify(player.equippedGearIds)}});
check('Gear enforces weight 6 and maximum 3',gear.toggles.slice(0,3).every(Boolean)&&!gear.toggles[3]&&gear.equipped.weight===6&&gear.equipped.ids.length===3);check('Equipped gear effects apply',gear.equipped.stats[0]===gear.base[0]+1&&gear.equipped.stats[1]===gear.base[1]+6&&gear.equipped.stats[2]===gear.base[2]+2);check('Gear changes are port-only',!gear.outside&&gear.unchanged);

await fresh();const drillCopy=await page.evaluate(()=>{const text=document.body.innerText;return{old:(text.match(/つるはし/g)||[]).length,drill:text.includes('船外削岩機'),power:text.includes('削岩出力'),blocked:!debugCraft('pickaxe')}});check('Player-facing copy consistently presents the airship rock drill',drillCopy.old===0&&drillCopy.drill&&drillCopy.power,JSON.stringify(drillCopy));check('Rock-drill upgrade keeps its material gate',drillCopy.blocked);

const terrain=await page.evaluate(()=>{const profiles=TERRAIN_PROFILES.map(x=>x.id),trips=[expedition.terrainProfileId];for(let i=0;i<11;i++){expedition.returnRequested=true;expedition.returnReason='manual';finishReturn();acknowledgeResult();debugDepart(1);trips.push(expedition.terrainProfileId)}return{profiles,trips}});check('Four terrain profiles exist',JSON.stringify(terrain.profiles)===JSON.stringify(['hills','spire','basin','twin']));check('Terrain varies across trips',new Set(terrain.trips).size>=3,JSON.stringify(terrain.trips));

// v0.7.3: the camera must frame the complete generated scene, including the
// crowns added after the original camera constants and the sentinel label.
// Direct generation lets this matrix cover both destinations and every terrain
// profile without depending on the route unlock state.
const fitViewports=[{name:'mobile-tall',width:390,height:844},{name:'mobile-short',width:375,height:667},{name:'desktop',width:1366,height:768},{name:'desktop-wide',width:1536,height:864}],fitSamples=[],mobileUiSamples=[];
for(const viewport of fitViewports){
  await page.setViewportSize({width:viewport.width,height:viewport.height});
  await page.waitForFunction(([width,height])=>viewW===width&&viewH===height,[viewport.width,viewport.height]);
  const samples=await page.evaluate(({viewportName})=>{const samples=[];for(const level of[1,2])for(let serial=1;serial<=24;serial++){tripSerial=serial;generateIsland(level);placeCreatures();placeTrees();setupEncounters();fitCameraToIsland();const fit=debugSceneFit(),safeWidth=fit.safe.right-fit.safe.left,safeHeight=fit.safe.bottom-fit.safe.top,sceneWidth=fit.bounds.right-fit.bounds.left,sceneHeight=fit.bounds.bottom-fit.bounds.top;const treeKinds=trees.filter(tree=>!tree.chopped&&!tree.fallen).reduce((counts,tree)=>{counts[tree.kind]=(counts[tree.kind]||0)+1;return counts},{}),required=DESTINATION_RESOURCE[level-1];samples.push({viewport:viewportName,level,serial,profile:expedition.terrainProfileId,bounds:fit.bounds,safe:fit.safe,distance:fit.distance,widthRatio:sceneWidth/safeWidth,heightRatio:sceneHeight/safeHeight,shortRatio:Math.min(sceneWidth,sceneHeight)/Math.min(safeWidth,safeHeight),inside:fit.bounds.left>=fit.safe.left-2&&fit.bounds.top>=fit.safe.top-2&&fit.bounds.right<=fit.safe.right+2&&fit.bounds.bottom<=fit.safe.bottom+2,trees:treeKinds,enemy:level===1||!!expedition.enemy?.hp,resource:cells.includes(required)})}return samples},{viewportName:viewport.name});
  fitSamples.push(...samples);
  if(viewport.width<=390){const ui=await page.evaluate(({viewportName})=>{Object.assign(expedition,{phase:'exploring',fuel:60,maxHull:3,hull:3});islandLevel=2;for(const chest of expedition.chests)chest.exposed=false;renderBase();updateHud();renderEncounter();fitCameraToIsland();const panel=document.getElementById('encounter-status'),safe=cameraSafeRect(),bounds=projectedSceneBounds();return{viewport:viewportName,panelHidden:panel.hidden,sceneInside:bounds.left>=safe.left-2&&bounds.top>=safe.top-2&&bounds.right<=safe.right+2&&bounds.bottom<=safe.bottom+2,bounds,safe}},{viewportName:viewport.name});mobileUiSamples.push(ui)}
}
const fitProfiles=new Set(fitSamples.map(sample=>sample.profile));
check('Initial camera contains every island, tree crown, and sentinel label at all target viewports',fitSamples.every(sample=>sample.inside),JSON.stringify(fitSamples.filter(sample=>!sample.inside).slice(0,8)));
const legible=sample=>sample.viewport==='mobile-short'?sample.shortRatio>=.42&&Math.max(sample.widthRatio,sample.heightRatio)>=.44:sample.shortRatio>=.62&&Math.max(sample.widthRatio,sample.heightRatio)>=.72;check('Scene remains comfortably legible instead of shrinking excessively',fitSamples.every(legible),JSON.stringify(fitSamples.map(({viewport,level,serial,profile,widthRatio,heightRatio,shortRatio})=>({viewport,level,serial,profile,widthRatio:+widthRatio.toFixed(2),heightRatio:+heightRatio.toFixed(2),shortRatio:+shortRatio.toFixed(2)})).filter(sample=>!legible(sample)).slice(0,8)));
check('Fit matrix covers all terrain profiles with the required trees, sentinel, and destination resource',fitProfiles.size===4&&fitSamples.every(sample=>sample.trees.sapling===6&&sample.trees.large===2&&sample.enemy&&sample.resource),JSON.stringify({profiles:[...fitProfiles],bad:fitSamples.filter(sample=>sample.trees.sapling!==6||sample.trees.large!==2||!sample.enemy||!sample.resource).slice(0,8)}));
check('Enemy information panel is absent during ordinary island 2 exploration',mobileUiSamples.length===2&&mobileUiSamples.every(sample=>sample.panelHidden),JSON.stringify(mobileUiSamples));
check('Mobile scene fit uses the space recovered from the removed enemy panel',mobileUiSamples.every(sample=>sample.sceneInside),JSON.stringify(mobileUiSamples.filter(sample=>!sample.sceneInside)));
const islandShape=await page.evaluate(()=>({baseDepth:ISLAND.baseDepth,depthPerLevel:ISLAND.depthPerLevel,topNoise:ISLAND.topNoise}));check('Island vertical generation is compressed from the pre-v0.7.3 constants',islandShape.baseDepth<7.6&&islandShape.depthPerLevel<1.1&&islandShape.topNoise<2.6,JSON.stringify(islandShape));

await page.setViewportSize({width:390,height:844});await page.waitForFunction(()=>viewW===390&&viewH===844);await page.evaluate(()=>{tripSerial=17;generateIsland(2);placeCreatures();placeTrees();setupEncounters();fitCameraToIsland();renderBase();markDirty();renderIslandLayer()});await page.screenshot({path:path.join(artifactDirectory,'island-fit-v073-mobile.png'),fullPage:true});
await page.setViewportSize({width:1366,height:768});await page.waitForFunction(()=>viewW===1366&&viewH===768);await page.evaluate(()=>{tripSerial=17;generateIsland(2);placeCreatures();placeTrees();setupEncounters();fitCameraToIsland();renderBase();markDirty();renderIslandLayer()});await page.screenshot({path:path.join(artifactDirectory,'island-fit-v073-desktop.png'),fullPage:true});

await fresh();const cameraBefore=await page.evaluate(()=>{debugDepart(1);return{target:[camTargetX,camTargetY,camTargetZ],focus:[camFocusX,camFocusY,camFocusZ],zoom:camera.zoom}});await page.evaluate(()=>{const center=(GX-1)/2;for(let y=0;y<GY;y++)for(let z=0;z<GZ;z++)for(let x=0;x<center-1;x++){const index=cellIndex(x,y,z);if(cells[index]){cells[index]=0;solidCount--}}rebuildSurface();focusDirty=true;markDirty()});await page.waitForTimeout(1300);const cameraFollow=await page.evaluate(()=>({target:[camTargetX,camTargetY,camTargetZ],focus:[camFocusX,camFocusY,camFocusZ]}));check('Mining centroid changes still produce smooth camera focus follow',Math.abs(cameraFollow.focus[0]-cameraBefore.focus[0])>.25&&Math.abs(cameraFollow.target[0]-cameraFollow.focus[0])<.08,JSON.stringify({before:cameraBefore,after:cameraFollow}));
await page.locator('#stage').dispatchEvent('wheel',{deltaY:-100});const manualZoom=await page.evaluate(()=>camera.zoom);check('Manual wheel zoom remains available after automatic fit',manualZoom>cameraBefore.zoom,`${cameraBefore.zoom} -> ${manualZoom}`);const savedCamera=await page.evaluate(()=>{saveGame();return{yaw:camera.yaw,pitch:camera.pitch,dist:camera.dist,zoom:camera.zoom,target:[camTargetX,camTargetY,camTargetZ]}});await page.reload();await page.waitForFunction(()=>typeof debugState==='function');const restoredCamera=await page.evaluate(()=>({yaw:camera.yaw,pitch:camera.pitch,dist:camera.dist,zoom:camera.zoom,target:[camTargetX,camTargetY,camTargetZ]})),cameraDelta=Math.max(...['yaw','pitch','dist','zoom'].map(key=>Math.abs(savedCamera[key]-restoredCamera[key])),...savedCamera.target.map((value,index)=>Math.abs(value-restoredCamera.target[index])));check('Reload restores fitted distance, manual zoom, and followed target',cameraDelta<.000001,JSON.stringify({savedCamera,restoredCamera,cameraDelta}));

await fresh();await page.evaluate(()=>{expedition.routeLevel=1;debugDepart(2)});s=await state();check('Island 2 starts sentinel on four-turn cycle',s.expedition.enemy?.attackEvery===4&&s.expedition.enemy.turnsUntilAttack===4&&s.expedition.hull===3);
const enemyVisual=await page.evaluate(()=>{const partBounds=(parts)=>{const axis=i=>[Math.min(...parts.map(part=>part[i])),Math.max(...parts.map(part=>part[i]+part[i+3]))];return[axis(0),axis(1),axis(2)]};const signature=faces=>({count:faces.length,colors:[...new Set(faces.map(face=>face.color))].sort()});const enemyParts=pose=>[...enemyBoxes(pose,false),...enemyEllipsoids(pose,false)],beetleParts=pose=>[...creatureBoxes('beetle',pose),...creatureEllipsoids('beetle',pose)];boilFrame=0;const first=buildPropFaces().filter(face=>face.entity.type==='enemy'),creature=creatures.find(entry=>entry.kind==='beetle'&&!entry.captured&&!entry.escaped),beetle=creature?buildPropFaces().filter(face=>face.entity.type==='creature'&&face.entity.id===creature.id):[];const firstParts=enemyParts(0),secondParts=enemyParts(1),normalEye=enemyEllipsoids(0,false)[3][6],warningEye=enemyEllipsoids(1,true)[3][6],normalLamp=enemyBoxes(0,false)[10][6],warningLamp=enemyBoxes(1,true)[10][6];return{first:{...signature(first),bounds:partBounds(firstParts)},beetle:{...signature(beetle),bounds:partBounds(beetleParts(0))},changed:JSON.stringify(firstParts)!==JSON.stringify(secondParts),feet:[Math.min(...firstParts.map(part=>part[1])),Math.min(...secondParts.map(part=>part[1]))],eyeChanged:JSON.stringify(normalEye)!==JSON.stringify(warningEye),lampChanged:JSON.stringify(normalLamp)!==JSON.stringify(warningLamp)}});
const extent=bounds=>bounds.map(([minimum,maximum])=>maximum-minimum),enemySize=extent(enemyVisual.first.bounds),beetleSize=extent(enemyVisual.beetle.bounds);
check('Sentinel has a dedicated mesh, palette, and larger silhouette than beetles',enemyVisual.first.count>0&&enemyVisual.beetle.count>0&&enemyVisual.first.count!==enemyVisual.beetle.count&&JSON.stringify(enemyVisual.first.colors)!==JSON.stringify(enemyVisual.beetle.colors)&&enemySize.every((size,index)=>size>beetleSize[index]),JSON.stringify(enemyVisual));
check('Sentinel two-frame motion changes articulated parts while its feet stay planted',enemyVisual.changed&&Math.abs(enemyVisual.feet[0]-enemyVisual.feet[1])<.001,JSON.stringify(enemyVisual.feet));
check('Sentinel eye and warning lamp change color before an attack',enemyVisual.eyeChanged&&enemyVisual.lampChanged,JSON.stringify(enemyVisual));
const enemyMarker=await page.evaluate(()=>{const read=()=>{const calls=[];const context={save(){},restore(){},beginPath(){},roundRect(x,y,w,h){calls.push({box:[x,y,w,h]})},fill(){},stroke(){},fillText(text,x,y){calls.push({text,x,y})},measureText(text){return{width:text.length*8}},set font(value){},set textAlign(value){},set textBaseline(value){},set fillStyle(value){},set strokeStyle(value){},set lineWidth(value){}};drawEnemyMarker(context);return calls};const expected=()=>{indexToXYZ(expedition.enemy.cellIndex,_xyz);cellToWorld(..._xyz,_w);return project(_w[0]+.5,_w[1]+4.05,_w[2]+.5).slice(0,2)};const first={calls:read(),expected:expected()};camera.yaw+=.7;updateCamBasis();updateViewDir();const rotated={calls:read(),expected:expected()};expedition.enemy.turnsUntilAttack=1;boilFrame=4;const warning=read();return{first,rotated,warning}});
const markerCalls=entry=>Array.isArray(entry)?entry:entry.calls,markerTexts=entry=>markerCalls(entry).filter(call=>call.text).map(call=>call.text),markerBox=entry=>markerCalls(entry).find(call=>call.box)?.box,near=(left,right)=>Math.hypot(left[0]-right[0],left[1]-right[1])<.01;
check('Sentinel overhead label shows name, four HP cells, and action countdown',JSON.stringify(markerTexts(enemyMarker.first))===JSON.stringify(['古代哨戒機','耐久 ■■■■','攻撃まで 4 作業'])&&markerTexts(enemyMarker.warning)[2]==='⚠ 次の作業で攻撃',JSON.stringify(enemyMarker));
check('Sentinel label follows its projected position after camera rotation',near([markerBox(enemyMarker.first)[0]+markerBox(enemyMarker.first)[2]/2,markerBox(enemyMarker.first)[1]+markerBox(enemyMarker.first)[3]/2],enemyMarker.first.expected)&&near([markerBox(enemyMarker.rotated)[0]+markerBox(enemyMarker.rotated)[2]/2,markerBox(enemyMarker.rotated)[1]+markerBox(enemyMarker.rotated)[3]/2],enemyMarker.rotated.expected)&&Math.hypot(...enemyMarker.first.expected.map((value,index)=>value-enemyMarker.rotated.expected[index]))>1,JSON.stringify(enemyMarker));
await page.setViewportSize({width:1280,height:900});await page.evaluate(()=>{expedition.enemy.turnsUntilAttack=4;camera.yaw=-.72;updateCamBasis();updateViewDir();markDirty();renderIslandLayer()});await page.screenshot({path:path.join(artifactDirectory,'enemy-world-ui-v074.png'),fullPage:true});
const enemyWorldUi=await page.evaluate(()=>{renderIslandLayer();const e=expedition.enemy,start={fuel:expedition.fuel,turns:expedition.turns,countdown:e.turnsUntilAttack,hp:e.hp},rect={...enemyMarkerHitRect},labelTap=debugTapAt((rect.left+rect.right)/2,(rect.top+rect.bottom)/2);return{start,rect,labelTap,after:{fuel:expedition.fuel,turns:expedition.turns,countdown:e.turnsUntilAttack,hp:e.hp},details:!document.getElementById('enemy-details').hidden,permanentPanel:!document.getElementById('encounter-status').hidden,attackButtons:[...document.querySelectorAll('#enemy-details button')].filter(button=>/攻撃/.test(button.textContent)).length}});
check('Tapping the world label opens details without spending fuel or advancing the enemy',enemyWorldUi.labelTap.enemyDetailsOpened&&enemyWorldUi.details&&JSON.stringify(enemyWorldUi.start)===JSON.stringify(enemyWorldUi.after),JSON.stringify(enemyWorldUi));
check('Enemy details contain no attack button and no enemy panel remains permanently visible',enemyWorldUi.attackButtons===0&&!enemyWorldUi.permanentPanel,JSON.stringify(enemyWorldUi));
const detailsBlocked=await page.evaluate(()=>({before:{fuel:expedition.fuel,turns:expedition.turns,countdown:expedition.enemy.turnsUntilAttack,yaw:camera.yaw,pitch:camera.pitch,zoom:camera.zoom},tap:debugTapAt(viewW/2,viewH/2)}));
await page.locator('#stage').dispatchEvent('pointerdown',{pointerId:41,clientX:300,clientY:300});await page.locator('#stage').dispatchEvent('pointermove',{pointerId:41,clientX:355,clientY:340});await page.locator('#stage').dispatchEvent('pointerup',{pointerId:41,clientX:355,clientY:340});await page.locator('#stage').dispatchEvent('wheel',{deltaY:-120});
const detailsAfterInput=await page.evaluate(before=>({before,after:{fuel:expedition.fuel,turns:expedition.turns,countdown:expedition.enemy.turnsUntilAttack,yaw:camera.yaw,pitch:camera.pitch,zoom:camera.zoom},visible:!document.getElementById('enemy-details').hidden}),detailsBlocked.before);
check('Enemy details block mining, attacks, drag, and wheel camera changes',detailsAfterInput.visible&&JSON.stringify(detailsAfterInput.before)===JSON.stringify(detailsAfterInput.after)&&!detailsBlocked.tap?.enemyAttacked&&detailsBlocked.tap?.broken===0,JSON.stringify({detailsBlocked,detailsAfterInput}));
await page.setViewportSize({width:390,height:844});const detailsTall=await page.evaluate(()=>{const card=document.querySelector('.enemy-details-card').getBoundingClientRect();return{left:card.left,top:card.top,right:card.right,bottom:card.bottom,width:innerWidth,height:innerHeight,visible:!document.getElementById('enemy-details').hidden}});await page.screenshot({path:path.join(artifactDirectory,'enemy-details-v074.png'),fullPage:true});
await page.locator('#btn-enemy-details-close').click();const closedByButton=await page.locator('#enemy-details').evaluate(element=>element.hidden);
await page.evaluate(()=>openEnemyDetails());await page.locator('#enemy-details').click({position:{x:2,y:2}});const closedByOverlay=await page.locator('#enemy-details').evaluate(element=>element.hidden);
await page.evaluate(()=>openEnemyDetails());await page.keyboard.press('Escape');const closedByEscape=await page.locator('#enemy-details').evaluate(element=>element.hidden);
await page.setViewportSize({width:375,height:667});await page.evaluate(()=>openEnemyDetails());const detailsShort=await page.evaluate(()=>{const card=document.querySelector('.enemy-details-card').getBoundingClientRect();return{left:card.left,top:card.top,right:card.right,bottom:card.bottom,width:innerWidth,height:innerHeight,visible:!document.getElementById('enemy-details').hidden}});await page.keyboard.press('Escape');
const sheetInside=sample=>sample.visible&&sample.left>=0&&sample.top>=0&&sample.right<=sample.width&&sample.bottom<=sample.height;
check('Enemy details close by button, overlay, and Escape',closedByButton&&closedByOverlay&&closedByEscape);
check('Enemy detail sheet fits 390x844 and 375x667 screens',sheetInside(detailsTall)&&sheetInside(detailsShort),JSON.stringify({detailsTall,detailsShort}));
await page.setViewportSize({width:390,height:844});const bodyAttack=await page.evaluate(()=>{markDirty();renderIslandLayer();const face=propPickFaces.find(candidate=>{if(candidate.entity.type!=='enemy')return false;const x=candidate.vertices.reduce((sum,p)=>sum+p[0],0)/candidate.vertices.length,y=candidate.vertices.reduce((sum,p)=>sum+p[1],0)/candidate.vertices.length;return visiblePropAt(x,y)?.entity.type==='enemy'&&!(enemyMarkerHitRect&&x>=enemyMarkerHitRect.left&&x<=enemyMarkerHitRect.right&&y>=enemyMarkerHitRect.top&&y<=enemyMarkerHitRect.bottom)});if(!face)return{missing:true};const x=face.vertices.reduce((sum,p)=>sum+p[0],0)/face.vertices.length,y=face.vertices.reduce((sum,p)=>sum+p[1],0)/face.vertices.length,e=expedition.enemy,before={fuel:expedition.fuel,turns:expedition.turns,countdown:e.turnsUntilAttack,hp:e.hp},result=debugTapAt(x,y);return{before,result,after:{fuel:expedition.fuel,turns:expedition.turns,countdown:e.turnsUntilAttack,hp:e.hp},point:[x,y]}});
check('Tapping the sentinel body attacks for exactly one fuel and one enemy turn',!bodyAttack.missing&&bodyAttack.result.enemyAttacked&&bodyAttack.after.fuel===bodyAttack.before.fuel-1&&bodyAttack.after.turns===bodyAttack.before.turns+1&&bodyAttack.after.countdown===bodyAttack.before.countdown-1&&bodyAttack.after.hp<bodyAttack.before.hp,JSON.stringify(bodyAttack));
const enemyPlacement=await page.evaluate(()=>{const samples=[],profiles=new Set;for(let serial=1;serial<=48;serial++){tripSerial=serial;islandLevel=2;generateIsland(2);placeCreatures();placeTrees();setupEncounters();profiles.add(expedition.terrainProfileId);const enemy=expedition.enemy;if(!enemy){samples.push({profile:expedition.terrainProfileId,missing:true});continue}indexToXYZ(enemy.cellIndex,_xyz);const xyz=[..._xyz],solid=!!cells[enemy.cellIndex],air=!cellAt(xyz[0],xyz[1]+1,xyz[2]),inside=xyz[0]>=0&&xyz[0]<GX&&xyz[1]>=0&&xyz[1]<GY&&xyz[2]>=0&&xyz[2]<GZ;const occupied=[...trees.filter(t=>!t.chopped&&!t.fallen).map(t=>t.cellIndex),...creatures.filter(c=>!c.captured&&!c.escaped).map(c=>c.cellIndex),...expedition.chests.map(c=>c.cellIndex)];const collision=occupied.includes(enemy.cellIndex);const bottoms=[];const originalBox=addPropBox,originalOval=addPropEllipsoid;addPropBox=function(faces,entity,origin,box,...rest){if(entity.type==='enemy')bottoms.push(origin[1]+box[1]*CREATURE_MESH_SCALE);return originalBox(faces,entity,origin,box,...rest)};addPropEllipsoid=function(faces,entity,origin,oval,...rest){if(entity.type==='enemy')bottoms.push(origin[1]+oval[1]*CREATURE_MESH_SCALE);return originalOval(faces,entity,origin,oval,...rest)};buildPropFaces();addPropBox=originalBox;addPropEllipsoid=originalOval;const meshMin=Math.min(...bottoms);cellToWorld(...xyz,_w);samples.push({profile:expedition.terrainProfileId,solid,air,inside,collision,mesh:bottoms.length>0,footDelta:Math.abs(meshMin-(_w[1]+1))})}return{profiles:[...profiles],samples}});
check('Island 2 sentinel stands safely on all four terrain profiles across trips',enemyPlacement.profiles.length===4&&enemyPlacement.samples.every(sample=>!sample.missing&&sample.solid&&sample.air&&sample.inside&&!sample.collision),JSON.stringify(enemyPlacement));
check('Sentinel mesh feet meet the supporting block top',enemyPlacement.samples.every(sample=>sample.mesh&&sample.footDelta<.001),JSON.stringify(enemyPlacement.samples.map(sample=>sample.footDelta)));
const enemyRelocation=await page.evaluate(()=>{tripSerial=73;islandLevel=2;generateIsland(2);placeCreatures();placeTrees();setupEncounters();const enemy=expedition.enemy,old=enemy?.cellIndex;if(!enemy)return{missing:true};cells[old]=0;solidCount--;relocateEnemy();const retreated=enemy.hp===0;const moved=!retreated&&enemy.cellIndex!==old&&enemyGroundIsSafe(enemy.cellIndex,1);const hull=expedition.hull,countdown=enemy.turnsUntilAttack;expedition.fuel=Math.max(1,expedition.fuel);beginAction();completeAction();return{retreated,moved,stopped:!retreated||expedition.hull===hull&&enemy.turnsUntilAttack===countdown}});check('Sentinel relocates after losing footing or retreats and stops attacking',!enemyRelocation.missing&&(enemyRelocation.moved||enemyRelocation.retreated)&&enemyRelocation.stopped,JSON.stringify(enemyRelocation));
await fresh();await page.evaluate(()=>{expedition.routeLevel=1;debugDepart(2)});
const turns=await page.evaluate(()=>{const e=expedition.enemy,start=e.turnsUntilAttack;camera.yaw+=.5;updateCamBasis();updateViewDir();renderIslandLayer();const free=e.turnsUntilAttack===start&&expedition.turns===0;for(let i=0;i<3;i++){beginAction();completeAction()}const calls=[],context={save(){},restore(){},beginPath(){},roundRect(){},fill(){},stroke(){},fillText(text){calls.push(text)},measureText(text){return{width:text.length*8}},set font(value){},set textAlign(value){},set textBaseline(value){},set fillStyle(value){},set strokeStyle(value){},set lineWidth(value){}};drawEnemyMarker(context);const warning=e.turnsUntilAttack===1&&calls.includes('⚠ 次の作業で攻撃'),h=expedition.hull;beginAction();completeAction();return{free,warning,attacked:expedition.hull===h-1,turns:expedition.turns}});check('Camera movement is zero turns',turns.free);check('Sentinel warns before attack in its world label',turns.warning);check('Sentinel attacks on fourth action',turns.attacked&&turns.turns===4);

await fresh();const chain=await page.evaluate(()=>{expedition.routeLevel=1;debugDepart(2);const e=expedition.enemy;cells.fill(0);damage.fill(0);creatures.length=0;trees.length=0;pendingBreaks.length=0;for(let x=2;x<6;x++)cells[cellIndex(x,2,2)]=M_COPPER;cells[cellIndex(7,2,2)]=M_STONE;solidCount=5;e.cellIndex=cellIndex(7,2,2);player.pickaxe=5;player.chain=1;expedition.fuel=20;e.turnsUntilAttack=4;rebuildSurface();mineAt(2,2,2,195,422);const during={threat:e.turnsUntilAttack,pending:pendingBreaks.length,turns:expedition.turns};nowSeconds+=100;processPendingBreaks();return{during,after:e.turnsUntilAttack,turns:expedition.turns}});check('Chain counts as one enemy turn',chain.during.pending>0&&chain.during.threat===4&&chain.after===3&&chain.turns===1,JSON.stringify(chain));

await fresh();const chest=await page.evaluate(()=>{expedition.routeLevel=1;debugDepart(2);const generated=expedition.chests.length;if(!generated)return{generated};const c=expedition.chests[0];indexToXYZ(c.cellIndex,_xyz);cells[cellIndex(_xyz[0]+1,_xyz[1],_xyz[2])]=0;updateChestExposure();const exposed=c.exposed,panel=!document.getElementById('encounter-status').hidden,title=document.getElementById('encounter-title').textContent,fuel=expedition.fuel,first=debugOpenChest(),panelAfter=document.getElementById('encounter-status').hidden,unlocked=player.workshopUnlocked,blueprints=player.blueprints,second=debugOpenChest();return{generated,exposed,panel,title,first,second,panelAfter,opened:c.opened,unlocked,blueprints,fuel,after:expedition.fuel}});check('Locked-workshop island 2 generates at least one real chest',chest.generated>=1);check('Only an exposed chest opens the contextual encounter panel',chest.exposed&&chest.panel&&chest.title==='埋没宝箱'&&chest.panelAfter,JSON.stringify(chest));check('Exposed chest costs one fuel and unlocks workshop',chest.exposed&&chest.first&&chest.opened&&chest.unlocked&&chest.blueprints===1&&chest.after===chest.fuel-1);check('Chest cannot be collected twice',!chest.second&&chest.blueprints===1);

await fresh();const defeat=await page.evaluate(()=>{expedition.routeLevel=1;debugDepart(2);openEnemyDetails();player.power=10;const n=player.gears.length,hit=debugAttackEnemy(),faces=buildPropFaces().filter(face=>face.entity.type==='enemy').length,calls=[],context={save(){},restore(){},beginPath(){},roundRect(){},fill(){},stroke(){},fillText(text){calls.push(text)},measureText(){return{width:10}},set font(value){},set textAlign(value){},set textBaseline(value){},set fillStyle(value){},set strokeStyle(value){},set lineWidth(value){}};drawEnemyMarker(context);return{hit,dead:expedition.enemy.hp===0,drop:player.gears.length===n+1,ids:expedition.gearIds.length,faces,labels:calls.length,detailsClosed:document.getElementById('enemy-details').hidden,markerCleared:enemyMarkerHitRect===null}});check('Sentinel defeat closes details and removes its mesh and label',defeat.hit&&defeat.dead&&defeat.drop&&defeat.ids===1&&defeat.faces===0&&defeat.labels===0&&defeat.detailsClosed&&defeat.markerCleared,JSON.stringify(defeat));
await fresh();const retreat=await page.evaluate(()=>{expedition.routeLevel=1;debugDepart(2);openEnemyDetails();cells.fill(0);solidCount=0;relocateEnemy();drawEnemyMarker({save(){},restore(){},beginPath(){},roundRect(){},fill(){},stroke(){},fillText(){},measureText(){return{width:10}},set font(value){},set textAlign(value){},set textBaseline(value){},set fillStyle(value){},set strokeStyle(value){},set lineWidth(value){}});return{retreated:expedition.enemy.hp===0,detailsClosed:document.getElementById('enemy-details').hidden,markerCleared:enemyMarkerHitRect===null}});check('Sentinel retreat closes details and removes its world label',retreat.retreated&&retreat.detailsClosed&&retreat.markerCleared,JSON.stringify(retreat));
await fresh();const creatureRegression=await page.evaluate(()=>{debugDepart(1);const creature=creatures.find(entry=>!entry.captured&&!entry.escaped);if(!creature)return{missing:true};const facesBefore=buildPropFaces().filter(face=>face.entity.type==='creature'&&face.entity.id===creature.id).length,fuel=expedition.fuel,originalProjection=creatureProjection;creatureProjection=entry=>entry.id===creature.id?{id:entry.id,x:viewW/2,y:viewH/2,depth:1}:originalProjection(entry);const captured=debugCapture(creature.id);creatureProjection=originalProjection;const facesAfter=buildPropFaces().filter(face=>face.entity.type==='creature'&&face.entity.id===creature.id).length;return{facesBefore,fuel,captured,facesAfter,fuelAfter:expedition.fuel,marked:creature.captured}});check('Ordinary creature mesh and capture behavior remain intact',!creatureRegression.missing&&creatureRegression.facesBefore>0&&creatureRegression.captured&&creatureRegression.facesAfter===0&&creatureRegression.fuelAfter===creatureRegression.fuel-1&&creatureRegression.marked,JSON.stringify(creatureRegression));
await fresh();const hull=await page.evaluate(()=>{expedition.routeLevel=1;debugDepart(2);expedition.hull=1;expedition.enemy.turnsUntilAttack=1;debugAttackEnemy();return{phase:expedition.phase,reason:expedition.returnReason,hull:expedition.hull}});check('Hull zero triggers result return',hull.phase==='result'&&hull.reason==='hull'&&hull.hull===0);

await fresh();const fuel=await page.evaluate(()=>{debugDepart(1);cells.fill(0);damage.fill(0);pendingBreaks.length=0;creatures.length=0;trees.length=0;cells[cellIndex(2,2,2)]=M_COPPER;cells[cellIndex(7,2,2)]=M_STONE;solidCount=2;rebuildSurface();expedition.fuel=1;player.pickaxe=5;player.power=20;player.range=0;player.chain=0;mineAt(2,2,2,195,422);return{phase:expedition.phase,requested:expedition.returnRequested,fuel:expedition.fuel,text:document.getElementById('fuel-notice-message').textContent,visible:!document.getElementById('fuel-notice').hidden}});check('Fuel depletion pauses at return message',fuel.phase==='exploring'&&fuel.requested&&fuel.fuel===0&&fuel.visible&&fuel.text==='燃料がなくなった。帰還しよう。');await page.evaluate(()=>debugAcknowledgeFuelNotice());check('Fuel notice proceeds to result',(await state()).expedition.phase==='result');
check('No runtime errors',errors.length===0,JSON.stringify(errors));
}finally{await browser.close()}if(fail.length){console.error(`\n${fail.length} failed: ${fail.join(', ')}`);process.exitCode=1}else console.log('\nAll voxel-mine v0.7 acceptance checks passed.');
